### ISSUE TITLE
Cannot deploy docker container

### ISSUE THREAD

**Issue by lupo112** [dzikoysk/reposilite#101]
Hi

I have a problem with deploying reposilite as docker service, see attached log.

```
14:31:37.257 INFO | 
14:31:37.261 INFO | Reposilite 2.5.2
14:31:37.263 INFO | 
14:31:37.264 INFO | --- Preparing workspace
14:31:37.266 INFO | Generating default configuration file.
14:31:37.295 INFO | 
Exception in thread "main" while parsing a block mapping
 in 'string', line 6, column 1:
    hostname: ""
    ^
expected <block end>, but found '<block sequence start>'
 in 'string', line 16, column 3:
      - "snapshots"
      ^
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:572)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:235)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:95)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:119)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:150)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:472)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:398)
	at org.panda_lang.reposilite.utils.YamlUtils.load(YamlUtils.java:43)
	at org.panda_lang.reposilite.config.ConfigurationLoader.load(ConfigurationLoader.java:45)
	at org.panda_lang.reposilite.Reposilite.launch(Reposilite.java:74)
	at org.panda_lang.reposilite.Reposilite.main(Reposilite.java:57)
14:31:38.275 INFO | Shutting down...
14:31:38.389 INFO | Stored records: 0
14:31:38.394 INFO | Bye! Uptime: 26521351.64min
```

Is there any steps that have to be done before deploy to docker?

Should be mapped any volumes to maintain persistency?

Your docs describes only that it should run when started, no additional config required.

**Comment by dzikoysk** [comment]
Oh, it's just a typo in latest release

![image](https://user-images.githubusercontent.com/4235722/83772257-7c074800-a683-11ea-9053-f351fe8f566d.png)

Thanks, I'll deploy a fix for a second.
