### ISSUE TITLE
Stop download from upstream for updated local file

### ISSUE THREAD

**Issue by a1730** [dzikoysk/reposilite#1212]
### Request details

We have replaced archiva with reposilite and we like it so far.

However, it is not clear to us how we could get reposilite to stop downloading from upstream when local files are newer.

Our particular need is for apache shiro artefacts that do not provide JPMS automatic-module-name. We patch the jars locally, recalculate the md5 and sha1 checksums. However, reposilite insists on downloading from upstream and overwriting our modifications. Is there a way to stop this behavior?

Thank you for reposilite - it is a gem.

**Comment by dzikoysk** [comment]
Hi, nice to hear it :)

It's quite interesting use-case. By the upstream, you mean some kind of other proxied repository, right? Also, what's your Reposilite version.

**Comment by a1730** [comment]
Yes, upstream is maven central which is proxied locally using reposilite.

We are using [Reposilite 3.0.0-alpha.23](https://repo.panda-lang.org/releases/org/panda-lang/reposilite/3.0.0-alpha.23/reposilite-3.0.0-alpha.23-all.jar)

I hope this helps.

**Comment by dzikoysk** [comment]
So Reposilite should always return local file if it exists:

https://github.com/dzikoysk/reposilite/blob/a252c698d3e2154906730c84067fdbd004d6079b/reposilite-backend/src/main/kotlin/com/reposilite/maven/MavenFacade.kt#L82

Only if the given file is not located, then proxied repository is requested. What's your setup and what's the name of this file? A situation you're describing may happen if you'd use sth like a 2 local repositories proxied through another local repository 🤔

**Comment by a1730** [comment]
Got it. Thanks for the swift response.
We decided not to move forward with shiro because of weak JPMS support - to may issues with split packages.

However, we noticed that Reposilite threw database exceptions when this happens (may not be related)

> 2022-04-07_11:18:38.54736 Exception in thread "Reposilite | IO (64) - 1" org.jetbrains.exposed.exceptions.ExposedSQLException: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO STATISTICS_RESOLVED_IDENTIFIER (""COUNT"", ""DATE"", IDENTIFIER_ID) VALUES (?, ?, ?) [*]ON DUPLICATE KEY UPDATE ""COUNT""=(STATISTICS_RESOLVED_IDENTIFIER.""COUNT"" + ?)"; SQL statement:
2022-04-07_11:18:38.54753 INSERT INTO STATISTICS_RESOLVED_IDENTIFIER ("COUNT", "DATE", IDENTIFIER_ID) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE "COUNT"=(STATISTICS_RESOLVED_IDENTIFIER."COUNT" + ?) [42000-210]
2022-04-07_11:18:38.54754 SQL: [Failed on expanding args for INSERT: net.dzikoysk.exposed.upsert.UpsertStatement@2508d73e]
2022-04-07_11:18:38.54758       at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:49)
2022-04-07_11:18:38.54758       at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:144)
2022-04-07_11:18:38.54759       at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:130)
2022-04-07_11:18:38.54759       at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:28)
2022-04-07_11:18:38.54760       at net.dzikoysk.exposed.upsert.ExposedUpsertExtensionsKt.upsert(ExposedUpsertExtensions.kt:17)
2022-04-07_11:18:38.54760       at net.dzikoysk.exposed.upsert.ExposedUpsertExtensionsKt.upsert$default(ExposedUpsertExtensions.kt:11)
2022-04-07_11:18:38.54764       at com.reposilite.statistics.infrastructure.SqlStatisticsRepository$incrementResolvedRequests$1.invoke(SqlStatisticsRepository.kt:75)
2022-04-07_11:18:38.54765       at com.reposilite.statistics.infrastructure.SqlStatisticsRepository$incrementResolvedRequests$1.invoke(SqlStatisticsRepository.kt:73)
2022-04-07_11:18:38.54765       at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:189)
2022-04-07_11:18:38.54765       at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1)
2022-04-07_11:18:38.54766       at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:215)
2022-04-07_11:18:38.54766       at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:223)
2022-04-07_11:18:38.54770       at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:214)
2022-04-07_11:18:38.54771       at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:165)
2022-04-07_11:18:38.54771       at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:223)
2022-04-07_11:18:38.54772       at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:135)
2022-04-07_11:18:38.54772       at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:132)
2022-04-07_11:18:38.54773       at com.reposilite.statistics.infrastructure.SqlStatisticsRepository.incrementResolvedRequests(SqlStatisticsRepository.kt:73)
2022-04-07_11:18:38.54773       at com.reposilite.statistics.StatisticsFacade.saveRecordsBulk(StatisticsFacade.kt:48)

There were many exceptions like the above. It may not be related.

As said above we are moving on from shiro, please feel free to close the issue.

**Comment by dzikoysk** [comment]
No, it's a bug with H2 integration (that is experimental target, by default we support only sqlite & mysql - it's covered by tests). I'll reference this in a new issue :)

**Comment by dzikoysk** [comment]
Fixed, unfortunately H2 does not support upserts and we had to change H2 dialect to MySQL. It means you'll need to recreate your database on a new version. In general I recommend to use stable db targets, H2 is a good option for temporary database where you don't really care about persistence of your data between restarts.

**Comment by dzikoysk** [comment]
Release with applied fix: https://github.com/dzikoysk/reposilite/releases/tag/3.0.0-alpha.24
