### ISSUE TITLE
Quota throws Exception

### ISSUE THREAD

**Issue by PlayerSchark** [dzikoysk/reposilite#1522]
### What happened?

I set the value in the settings Quota to "20GB " a value like "20GB" works fine. But if you add a space at the end Reposilite will throw an exception.

### Reposilite version

3.x

### Relevant log output

```shell
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.531 ERROR | Cannot load private repository
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.531 ERROR | java.lang.NumberFormatException: For input string: "20GB "
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.531 ERROR | 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.531 ERROR | 	at java.base/java.lang.Long.parseLong(Long.java:711)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.532 ERROR | 	at java.base/java.lang.Long.parseLong(Long.java:836)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.532 ERROR | 	at com.reposilite.storage.filesystem.FileSystemStorageProviderFactory$Companion.displaySizeToBytesCount(FileSystemStorageProviderFactory.kt:62)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.532 ERROR | 	at com.reposilite.storage.filesystem.FileSystemStorageProviderFactory$Companion.of(FileSystemStorageProviderFactory.kt:41)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.532 ERROR | 	at com.reposilite.storage.filesystem.FileSystemStorageProviderFactory.create(FileSystemStorageProviderFactory.kt:89)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.532 ERROR | 	at com.reposilite.storage.filesystem.FileSystemStorageProviderFactory.create(FileSystemStorageProviderFactory.kt:25)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.532 ERROR | 	at com.reposilite.storage.StorageFacade.createStorageProvider(StorageFacade.kt:16)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.532 ERROR | 	at com.reposilite.maven.RepositoryFactory.createRepository(RepositoryFactory.kt:47)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.532 ERROR | 	at com.reposilite.maven.RepositoryProvider$createRepositories$1.invoke(RepositoryProvider.kt:55)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.532 ERROR | 	at com.reposilite.maven.RepositoryProvider$createRepositories$1.invoke(RepositoryProvider.kt:54)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.532 ERROR | 	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.532 ERROR | 	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.532 ERROR | 	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.532 ERROR | 	at com.reposilite.maven.RepositoryProvider.createRepositories(RepositoryProvider.kt:72)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.532 ERROR | 	at com.reposilite.maven.RepositoryProvider._init_$lambda-1(RepositoryProvider.kt:39)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.532 ERROR | 	at panda.std.reactive.Reference.lambda$subscribe$1(Reference.java:55)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.532 ERROR | 	at panda.std.reactive.Reference.lambda$notifySubscribers$0(Reference.java:50)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.532 ERROR | 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.533 ERROR | 	at panda.std.reactive.Reference.notifySubscribers(Reference.java:50)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.533 ERROR | 	at panda.std.reactive.Reference.set(Reference.java:45)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.533 ERROR | 	at panda.std.reactive.Reference.lambda$computed$3(Reference.java:89)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.533 ERROR | 	at panda.std.reactive.Reference.lambda$subscribe$1(Reference.java:55)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.533 ERROR | 	at panda.std.reactive.Reference.lambda$notifySubscribers$0(Reference.java:50)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.533 ERROR | 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.533 ERROR | 	at panda.std.reactive.Reference.notifySubscribers(Reference.java:50)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.533 ERROR | 	at panda.std.reactive.Reference.set(Reference.java:45)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.533 ERROR | 	at panda.std.reactive.MutableReference.update(MutableReference.java:29)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.533 ERROR | 	at com.reposilite.configuration.shared.SharedConfigurationFacade$1$2.invoke(SharedConfigurationFacade.kt:33)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.533 ERROR | 	at com.reposilite.configuration.shared.SharedConfigurationFacade$1$2.invoke(SharedConfigurationFacade.kt:28)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.533 ERROR | 	at com.reposilite.configuration.shared.DefaultSharedSettingsReference.update$lambda-1(SharedSettingsReference.kt:38)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.533 ERROR | 	at panda.std.Result.supplyThrowing(Result.java:133)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.533 ERROR | 	at panda.std.Result.supplyThrowing(Result.java:125)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.533 ERROR | 	at com.reposilite.configuration.shared.DefaultSharedSettingsReference.update(SharedSettingsReference.kt:38)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.533 ERROR | 	at com.reposilite.configuration.shared.SharedConfigurationFacade.updateSharedSettings(SharedConfigurationFacade.kt:85)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.533 ERROR | 	at com.reposilite.configuration.shared.infrastructure.SettingsEndpoints$updateConfiguration$1$1.invoke(SettingsEndpoints.kt:121)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.533 ERROR | 	at com.reposilite.configuration.shared.infrastructure.SettingsEndpoints$updateConfiguration$1$1.invoke(SettingsEndpoints.kt:116)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.533 ERROR | 	at com.reposilite.shared.ContextDsl$managerOnly$1.invoke(ContextDsl.kt:80)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.534 ERROR | 	at com.reposilite.shared.ContextDsl$managerOnly$1.invoke(ContextDsl.kt:78)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.534 ERROR | 	at com.reposilite.shared.ContextDsl$authenticated$2.accept(ContextDsl.kt:59)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.534 ERROR | 	at com.reposilite.shared.ContextDsl$authenticated$2.accept(ContextDsl.kt:59)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.534 ERROR | 	at panda.std.Result.peek(Result.java:252)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.534 ERROR | 	at com.reposilite.shared.ContextDsl.authenticated(ContextDsl.kt:59)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.534 ERROR | 	at com.reposilite.shared.ContextDsl.managerOnly(ContextDsl.kt:78)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.534 ERROR | 	at com.reposilite.configuration.shared.infrastructure.SettingsEndpoints$updateConfiguration$1.invoke(SettingsEndpoints.kt:116)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.534 ERROR | 	at com.reposilite.configuration.shared.infrastructure.SettingsEndpoints$updateConfiguration$1.invoke(SettingsEndpoints.kt:115)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.534 ERROR | 	at com.reposilite.web.application.JavalinConfiguration$configureReactiveRoutingPlugin$plugin$1.invoke(JavalinConfiguration.kt:121)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.534 ERROR | 	at com.reposilite.web.application.JavalinConfiguration$configureReactiveRoutingPlugin$plugin$1.invoke(JavalinConfiguration.kt:108)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.534 ERROR | 	at com.reposilite.web.routing.RoutingPlugin.createHandler$lambda-3(RoutingPlugin.kt:38)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.534 ERROR | 	at io.javalin.routing.HandlerEntry.handle(HandlerEntry.kt:19)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.534 ERROR | 	at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:48)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.534 ERROR | 	at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.534 ERROR | 	at io.javalin.http.JavalinServletHandler$executeNextTask$2$1.invoke(JavalinServletHandler.kt:105)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.534 ERROR | 	at io.javalin.http.JavalinServletHandler$executeNextTask$2$1.invoke(JavalinServletHandler.kt:105)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.534 ERROR | 	at io.javalin.http.JavalinServletHandler.handleFutureResultReference(JavalinServletHandler.kt:128)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.534 ERROR | 	at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:105)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.534 ERROR | 	at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-0(JavalinServletHandler.kt:93)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.535 ERROR | 	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.535 ERROR | 	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.535 ERROR | 	at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:93)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.535 ERROR | 	at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:94)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.535 ERROR | 	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.535 ERROR | 	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.535 ERROR | 	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.535 ERROR | 	at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:94)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.535 ERROR | 	at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:94)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.535 ERROR | 	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.535 ERROR | 	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.535 ERROR | 	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.535 ERROR | 	at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:94)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.535 ERROR | 	at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:94)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.535 ERROR | 	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.535 ERROR | 	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.535 ERROR | 	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.535 ERROR | 	at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:94)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.535 ERROR | 	at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:96)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.535 ERROR | 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.536 ERROR | 	at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.536 ERROR | 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.536 ERROR | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.536 ERROR | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.536 ERROR | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.536 ERROR | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1571)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.536 ERROR | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.536 ERROR | 	at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:57)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.536 ERROR | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.536 ERROR | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.536 ERROR | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1544)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.536 ERROR | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.536 ERROR | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1297)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.536 ERROR | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.536 ERROR | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.536 ERROR | 	at org.eclipse.jetty.server.Server.handle(Server.java:562)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.536 ERROR | 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.536 ERROR | 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.537 ERROR | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.537 ERROR | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.537 ERROR | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.537 ERROR | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.537 ERROR | 	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.537 ERROR | 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.537 ERROR | 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.537 ERROR | 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.537 ERROR | 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:138)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.537 ERROR | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:407)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.537 ERROR | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.537 ERROR | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
com.reposilite.journalist.slf4j.Slf4jLogger 2022-08-30 22:18:09.537 ERROR | 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by dzikoysk** [comment]
Thanks, I've linked this in JsonForms issue that is related to several problems we have with this library [*]
