### ISSUE TITLE
EofException: Early EOF

### ISSUE THREAD

**Issue by mhfhyh** [dzikoysk/reposilite#1621]
Hi , I am facing issue when I try to deploy using maven plugin 

 Reposilite 2.9.26

     <distributionManagement>
		<repository>
			<id>my-repository</id>
			<url>http://remot-host:8443/snapshots</url>
		</repository>
	</distributionManagement>

org.eclipse.jetty.io.EofException: Early EOF
	at org.eclipse.jetty.server.HttpInput$3.getError(HttpInput.java:1207)
	at org.eclipse.jetty.server.HttpInput$3.noContent(HttpInput.java:1195)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:333)
	at java.io.InputStream.read(InputStream.java:101)
	at java.nio.file.Files.copy(Files.java:2908)
	at java.nio.file.Files.copy(Files.java:3027)
	at org.panda_lang.reposilite.repository.RepositoryStorage.storeFile(RepositoryStorage.java:121)
	at org.panda_lang.reposilite.repository.RepositoryStorage.storeFile(RepositoryStorage.java:94)
	at org.panda_lang.reposilite.repository.RepositoryService.lambda$storeFile$2(RepositoryService.java:70)
	at org.panda_lang.reposilite.repository.RepositoryService.tryExecute(RepositoryService.java:82)
	at org.panda_lang.reposilite.repository.RepositoryService.storeFile(RepositoryService.java:69)
	at org.panda_lang.reposilite.repository.DeployService.deploy(DeployService.java:97)
	at org.panda_lang.reposilite.repository.DeployEndpoint.handle(DeployEndpoint.java:76)
	at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:20)
	at io.javalin.http.JavalinServlet.addHandler$lambda-5(JavalinServlet.kt:114)
	at io.javalin.http.JavalinServlet$service$tryBeforeAndEndpointHandlers$1.invoke(JavalinServlet.kt:43)
	at io.javalin.http.JavalinServlet$service$tryBeforeAndEndpointHandlers$1.invoke(JavalinServlet.kt:38)
	at io.javalin.http.JavalinServlet.service$tryWithExceptionMapper(JavalinServlet.kt:130)
	at io.javalin.http.JavalinServlet.service$tryBeforeAndEndpointHandlers(JavalinServlet.kt:38)
	at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:86)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:52)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:750)

**Comment by joshuasing** [comment]
Hello, I have not experienced this using the latest version of Reposilite.
Is there a reason as to why you are using a legacy version? If not, I would highly recommend upgrading :)

**Comment by mhfhyh** [comment]
As I understood from Doc of 3.0> versions it seems that it needs DB connection . This is the only reason

**Comment by dzikoysk** [comment]
That's true, but by default it uses embedded sqlite instance, so you don't need to create your own instance if you don't want to.
