### ISSUE TITLE
Exception in help command destroys console connection

### ISSUE THREAD

**Issue by Koboo** [dzikoysk/reposilite#1630]
### What happened?

First of all, I would like to thank all the contributors! Reposilite has been my go-to since at least version 2! Keep up the good work!

When I execute "help <unknown-command>", an exception is thrown. Unfortunately, this exception breaks the connection of the console and you can't use it anymore. The connection is only reestablished once you switch to another tab and back to the console.

Step 1:
![Step 1](https://i.imgur.com/7nvYQq5.png)

Step 2:
![Step 2](https://i.imgur.com/WG3KIVj.png)

Furthermore, the StackTrace is unfortunately listed on one line, so [I formatted it](https://elmah.io/tools/stack-trace-formatter/).

### Reposilite version

3.x

### Relevant log output

```shell
11:30:53.515 WARN | Uncaught exception in WebSocket handler: java.lang.IllegalStateException: Unknown command 'route-'
   at com.reposilite.shared.extensions.PicocliExtensionsKt.createCommandHelp(PicocliExtensions.kt:48 undefined)
   at com.reposilite.console.HelpCommand.execute(StandardCommands.kt:37 undefined)
   at com.reposilite.console.CommandExecutor.executeCommand(CommandExecutor.kt:70 undefined)
   at com.reposilite.console.CommandExecutor.execute(CommandExecutor.kt:46 undefined)
   at com.reposilite.console.CommandExecutor.execute(CommandExecutor.kt:43 undefined)
   at com.reposilite.console.ConsoleFacade.executeCommand(ConsoleFacade.kt:47) at com.reposilite.console.infrastructure.CliEndpoint.accept$lambda-4(ConsoleWebSocketHandler.kt:88)
   at io.javalin.websocket.WsConnection$onMessage$1.invoke(WsConnection.kt:38 undefined)
   at io.javalin.websocket.WsConnection$onMessage$1.invoke(WsConnection.kt:38 undefined)
   at io.javalin.websocket.WsConnection.tryBeforeAndEndpointHandlers(WsConnection.kt:72 undefined)
   at io.javalin.websocket.WsConnection.onMessage(WsConnection.kt:38 undefined)
   at org.eclipse.jetty.websocket.core.internal.messages.StringMessageSink.accept(StringMessageSink.java:53 undefined)
   at org.eclipse.jetty.websocket.common.JettyWebSocketFrameHandler.acceptMessage(JettyWebSocketFrameHandler.java:334 undefined)
   at org.eclipse.jetty.websocket.common.JettyWebSocketFrameHandler.onTextFrame(JettyWebSocketFrameHandler.java:422 undefined)
   at org.eclipse.jetty.websocket.common.JettyWebSocketFrameHandler.onFrame(JettyWebSocketFrameHandler.java:240 undefined)
   at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession$IncomingAdaptor.lambda$onFrame$1(WebSocketCoreSession.java:671 undefined)
   at org.eclipse.jetty.serverr.ContextHandler.handle.handle(ContextHandler.java:1465 undefined)
   at org.eclipse.jetty.serverr.ContextHandler.handle.handle(ContextHandler.java:1484 undefined)
   at org.eclipse.jetty.websocket.core.server.internal.AbstractHandshaker$1.handle(AbstractHandshaker.java:212 undefined)
   at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession$IncomingAdaptor.onFrame(WebSocketCoreSession.java:671 undefined)
   at org.eclipse.jetty.websocket.core.AbstractExtension.nextIncomingFrame(AbstractExtension.java:144 undefined)
   at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension.nextIncomingFrame(PerMessageDeflateExtension.java:236 undefined)
   at org.eclipse.jetty.websocket.core.internal.DemandingFlusher.emitFrame(DemandingFlusher.java:145 undefined)
   at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension$IncomingFlusher.inflate(PerMessageDeflateExtension.java:480 undefined)
   at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension$IncomingFlusher.handle(PerMessageDeflateExtension.java:413 undefined)
   at org.eclipse.jetty.websocket.core.internal.DemandingFlusher.process(DemandingFlusher.java:169 undefined)
   at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:232 undefined)
   at org.eclipse.jetty.util.IteratingCallback.succeeded(IteratingCallback.java:350 undefined)
   at org.eclipse.jetty.websocket.core.internal.DemandingFlusher.onFrame(DemandingFlusher.java:104 undefined)
   at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension.onFrame(PerMessageDeflateExtension.java:93 undefined)
   at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:120 undefined)
   at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.onFrame(WebSocketCoreSession.java:481 undefined)
   at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:262 undefined)
   at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:455 undefined)
   at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:340 undefined)
   at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314 undefined)
   at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100 undefined)
   at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53 undefined)
   at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421 undefined)
   at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390 undefined)
   at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277 undefined)
   at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:139 undefined)
   at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411 undefined)
   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:933 undefined)
   at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1077 undefined)
   at java.base/java.lang.Thread.run(Thread.java:833 undefined)
```

**Comment by dzikoysk** [comment]
Thanks! There was a missing import to proper error method, so it used a throwing variant from Kotlin std. `3.1.1` with that fix should be available within an hour :)
