### ISSUE TITLE
Reposilite doesn't work with SSL certificate

### ISSUE THREAD

**Issue by JNNGL** [dzikoysk/reposilite#1696]
### What happened?

Reposilite throws an exception when trying to use a certificate in .pem format (for both Let's Encrypt and self-signed certificates)
I also tried to convert the certificate to .jks format, Reposilite starts up, but when I try to connect, it gives this error:
<img width=66% height=66% src="https://cdn.discordapp.com/attachments/1063171690823176293/1066674718771523696/image.png">

Reposilite 3.0.0 works fine with certificate in .jks format.

### Reposilite version

3.x

### Relevant log output

```shell
Stack trace (SSL certificate in .pem format):
nl.altindag.ssl.exception.PrivateKeyParseException: Received an unsupported private key type
    at nl.altindag.ssl.util.PemUtils.lambda$parsePrivateKey$11(PemUtils.java:484)
    at java.base/java.util.Optional.orElseThrow(Optional.java:403)
    at nl.altindag.ssl.util.PemUtils.parsePrivateKey(PemUtils.java:484)
    at nl.altindag.ssl.util.PemUtils.parseIdentityMaterial(PemUtils.java:395)
    at nl.altindag.ssl.util.PemUtils.loadIdentityMaterial(PemUtils.java:367)
    at nl.altindag.ssl.util.PemUtils.loadIdentityMaterial(PemUtils.java:298)
    at io.javalin.community.ssl.util.SSLUtils.parseIdentity(SSLUtils.java:81)
    at io.javalin.community.ssl.util.SSLUtils.getSslFactory(SSLUtils.java:51)
    at io.javalin.community.ssl.util.SSLUtils.getSslFactory(SSLUtils.java:37)
    at io.javalin.community.ssl.SSLPlugin.createJettyServerPatcher(SSLPlugin.java:143)
    at io.javalin.community.ssl.SSLPlugin.apply(SSLPlugin.java:76)
    at io.javalin.plugin.PluginManager.initializePlugins(PluginManager.kt:38)
    at io.javalin.config.JavalinConfig$Companion.applyUserConfig(JavalinConfig.kt:47)
    at io.javalin.config.JavalinConfig.applyUserConfig(JavalinConfig.kt)
    at io.javalin.Javalin.create(Javalin.java:93)
    at com.reposilite.web.HttpServer.createJavalin(HttpServer.kt:65)
    at com.reposilite.web.HttpServer.start(HttpServer.kt:45)
    at com.reposilite.Reposilite.launch(Reposilite.kt:64)
    at com.reposilite.ReposiliteLauncherKt.main(ReposiliteLauncher.kt:22)
```

**Comment by dzikoysk** [comment]
Could you show your `keyPath` configuration?

**Comment by JNNGL** [comment]
> Could you show your `keyPath` configuration?

<img src="https://cdn.discordapp.com/attachments/744350458910605433/1066840152229548072/image.png">
<img src="https://cdn.discordapp.com/attachments/744350458910605433/1066840415107559526/image.png">

> Also, here's a guide how to generate valid certificates: (we're using this plugin directly in Reposilite)

It gives the same error with self-signed certificates:
<img width=100% height=100% src="https://cdn.discordapp.com/attachments/744350458910605433/1066843597711880323/image.png">
<img src="https://cdn.discordapp.com/attachments/744350458910605433/1066843740850901013/image.png">

**Comment by dzikoysk** [comment]
Could you swap key with cert in configuration, so the cert path is first?

**Comment by JNNGL** [comment]
![image](https://user-images.githubusercontent.com/45935949/213943751-47d3d31e-3ea4-42aa-9d79-3486d4833553.png)
![image](https://user-images.githubusercontent.com/45935949/213943767-e6b91a2a-9fce-4d1c-91d8-f1badaf23320.png)

**Comment by dzikoysk** [comment]
It should work properly in 3.2.7:

* https://github.com/dzikoysk/reposilite/releases/tag/3.2.7
