### ISSUE TITLE
Error finalising cipher/No Cipher Suite matching '...' is supported

### ISSUE THREAD

**Issue by JNNGL** [dzikoysk/reposilite#1698]
### What happened?

When using a Let's Encrypt certificate, Reposilite prints "No Cipher Suite matching '...' is supported" message (for both .pem and .jks formats). 
When using a self-signed certificate it throws BadPaddingException.

### Reposilite version

3.x

### Relevant log output

```shell
With Let's Encrypt certificate:
No Cipher Suite matching 'TLS_DHE_RSA_WITH_AES_256_GCM_SHA384' is supported
No Cipher Suite matching 'TLS_DHE_RSA_WITH_AES_128_GCM_SHA256' is supported

With self-signed certificate:
nl.altindag.ssl.exception.PrivateKeyParseException: org.bouncycastle.pkcs.PKCSException: unable to read encrypted data: Error finalising cipher
   at nl.altindag.ssl.util.PemUtils.extractPrivateKeyInfo(PemUtils.java:508)
   at nl.altindag.ssl.util.PemUtils.lambda$parsePrivateKey$10(PemUtils.java:479)
   at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
   at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
   at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
   at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
   at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
   at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
   at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
   at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
   at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
   at nl.altindag.ssl.util.PemUtils.parsePrivateKey(PemUtils.java:482)
   at nl.altindag.ssl.util.PemUtils.parseIdentityMaterial(PemUtils.java:395)
   at nl.altindag.ssl.util.PemUtils.loadIdentityMaterial(PemUtils.java:367)
   at nl.altindag.ssl.util.PemUtils.loadIdentityMaterial(PemUtils.java:298)
   at io.javalin.community.ssl.util.SSLUtils.parseIdentity(SSLUtils.java:81)
   at io.javalin.community.ssl.util.SSLUtils.getSslFactory(SSLUtils.java:51)
   at io.javalin.community.ssl.util.SSLUtils.getSslFactory(SSLUtils.java:37)
   at io.javalin.community.ssl.SSLPlugin.createJettyServerPatcher(SSLPlugin.java:143)
   at io.javalin.community.ssl.SSLPlugin.apply(SSLPlugin.java:76)
   at io.javalin.plugin.PluginManager.initializePlugins(PluginManager.kt:38)
   at io.javalin.config.JavalinConfig$Companion.applyUserConfig(JavalinConfig.kt:47)
   at io.javalin.config.JavalinConfig.applyUserConfig(JavalinConfig.kt)
   at io.javalin.Javalin.create(Javalin.java:93)
   at com.reposilite.web.HttpServer.createJavalin(HttpServer.kt:65)
   at com.reposilite.web.HttpServer.start(HttpServer.kt:45)
   at com.reposilite.Reposilite.launch(Reposilite.kt:64)
   at com.reposilite.ReposiliteLauncherKt.main(ReposiliteLauncher.kt:22)
Caused by: org.bouncycastle.pkcs.PKCSException: unable to read encrypted data: Error finalising cipher
   at org.bouncycastle.pkcs.PKCS8EncryptedPrivateKeyInfo.decryptPrivateKeyInfo(Unknown Source)
   at nl.altindag.ssl.decryptor.BouncyFunction.lambda$andThen$0(BouncyFunction.java:37)
   at nl.altindag.ssl.util.PemUtils.extractPrivateKeyInfo(PemUtils.java:496)
   ... 27 more
Caused by: org.bouncycastle.crypto.io.InvalidCipherTextIOException: Error finalising cipher
   at org.bouncycastle.jcajce.io.CipherInputStream.finaliseCipher(Unknown Source)
   at org.bouncycastle.jcajce.io.CipherInputStream.nextChunk(Unknown Source)
   at org.bouncycastle.jcajce.io.CipherInputStream.read(Unknown Source)
   at org.bouncycastle.util.io.Streams.pipeAll(Unknown Source)
   at org.bouncycastle.util.io.Streams.pipeAll(Unknown Source)
   at org.bouncycastle.util.io.Streams.readAll(Unknown Source)
   ... 30 more
Caused by: javax.crypto.BadPaddingException: pad block corrupted
   at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$BufferedGenericBlockCipher.doFinal(Unknown Source)
   at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(Unknown Source)
   at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2090)
   ... 36 more
```

**Comment by dzikoysk** [comment]
Does it throw with these cert/key?

* https://github.com/dzikoysk/reposilite/tree/main/reposilite-backend/src/test/workspace

Password: reposilite

**Comment by JNNGL** [comment]
> Does it throw with these cert/key?

No, but it prints "No Cipher Suite matching '...' is supported" message and I'm unable to connect
![image](https://user-images.githubusercontent.com/45935949/214041575-f77950f3-d85e-425e-91f5-fecd1f383530.png)
![image](https://user-images.githubusercontent.com/45935949/214040385-2c603466-ffd0-4ad9-af5d-2202d0e4190f.png)

> Also, what's your Java version and system?

![image](https://user-images.githubusercontent.com/45935949/214040495-79bb8963-3ce0-432e-8d26-724b965c2486.png)
![image](https://user-images.githubusercontent.com/45935949/214040660-bd98f6b8-3efb-4674-9575-cb74cec915bd.png)

**Comment by dzikoysk** [comment]
> With Let's Encrypt certificate:
> ```
> No Cipher Suite matching 'TLS_DHE_RSA_WITH_AES_256_GCM_SHA384' is supported
> No Cipher Suite matching 'TLS_DHE_RSA_WITH_AES_128_GCM_SHA256' is supported
> ``` 

As far as I see it's just an info message from underlying crypto libs, you should be able to connect to the instance on ::443 port:

![obraz](https://user-images.githubusercontent.com/4235722/214128754-d25bcab8-0524-49d7-a150-f486aa9cc737.png)

I'm not sure about the throwing, `Caused by: javax.crypto.BadPaddingException: pad block corrupted` sounds like an issue with invalid certificate 🤔

**Comment by hevav** [comment]
> Does it throw with these cert/key?
I've set these cert/key to my config, and I get ``curl: (92) HTTP/2 stream 1 was not closed cleanly before end of the underlying stream`` error when I'm trying to execute ``curl https://localhost -k`` command.
But everything works for me when I add ``--http1.1`` flag to curl

**Comment by dzikoysk** [comment]
Do you use reverse proxy serice like e.g. Nginx?

**Comment by hevav** [comment]
I don't use reverse proxy service, I just launched the reposilite jar file with default config but changed keyPath/password.

**Comment by dzikoysk** [comment]
I see, to be fair I don't know much about certificates in general, but JKS should still work tho. By default JVM handles only JKS certs, so I used Javalin plugin to support PEM:

* https://github.com/javalin/javalin-ssl

That is based on top of this library:

* https://github.com/Hakky54/sslcontext-kickstart

And that's basically it. @zugazagoitia do you know what might be the cause?

**Comment by dzikoysk** [comment]
Connector starts with `http/1.1`:

```
23:40:27.537 INFO | Started ServerConnector@30c3ae63{SSL, (ssl, alpn, h2, http/1.1)}{0.0.0.0:443}
```

I guess that's why you have to downgrade protocol in curl. I wonder if it's related to missing cipher suite.

**Comment by zugazagoitia** [comment]
> Connector starts with `http/1.1`:
> 
> ```
> 23:40:27.537 INFO | Started ServerConnector@30c3ae63{SSL, (ssl, alpn, h2, http/1.1)}{0.0.0.0:443}
> ```
> 
> I guess that's why you have to downgrade protocol in curl. I wonder if it's related to missing cipher suite.

It's starting both, H2 and http1.1, including a ALPN extension that should upgrade any http1.1 connection by default if supported.

**Comment by zugazagoitia** [comment]
@JNNGL 
> When using a Let's Encrypt certificate, Reposilite prints "No Cipher Suite matching '...' is supported" message (for both .pem and .jks formats). 

That is completely normal, they show up because I'm setting Mozilla's recommended settings (https://wiki.mozilla.org/Security/Server_Side_TLS) and some JVM providers/conscrypt might not support some of them. But every single other cipher suit should work, and that's enough.

> When using a self-signed certificate it throws BadPaddingException.

This looks like a wrong password/key, from what I can see in the stack trace. Sadly without them I can't reproduce it.

**Comment by zugazagoitia** [comment]
> I've set these cert/key to my config, and I get `curl: (92) HTTP/2 stream 1 was not closed cleanly before end of the underlying stream` error when I'm trying to execute `curl https://localhost -k` command. But everything works for me when I add `--http1.1` flag to curl
> 
> `curl https://localhost -k` without `--http1.1` works well on Reposilite 3.0.0 (I haven't checked other versions yet)

Could you please give me some more context to investigate, I understand this works in Reposilite 3.0.0 but not on a newer version? Also what's your OS/JVM?

**Comment by dzikoysk** [comment]
3.0.0 used built-in Jetty's SSL API to enable JKS certifacte, in 3.1.0 we moved to javalin-ssl plugin:

* https://github.com/dzikoysk/reposilite/issues/1591

That's why JKS worked before, but it's not on http2 on Reposilite 3.1.0+. I didn't try to verify this behavior on earlier versions on my own, I may try later today.

**Comment by JNNGL** [comment]
> The date is wrong, given that the screenshot was taken yesterday. Set it correctly and that would let you connect.

Jan 5 is the date when the kernel was compiled.
The system date is correct:
![image](https://user-images.githubusercontent.com/45935949/214327025-73fa06c8-a523-4657-9ed4-09abb4e81596.png)

**Comment by zugazagoitia** [comment]
> > The date is wrong, given that the screenshot was taken yesterday. Set it correctly and that would let you connect.
> 
> Jan 5 is the date when the kernel was compiled.
> The system date is correct:
> ![image](https://user-images.githubusercontent.com/45935949/214327025-73fa06c8-a523-4657-9ed4-09abb4e81596.png)
> 

My bad!

**Comment by AVuTuVA** [comment]
I have the same problem

**Comment by dzikoysk** [comment]
@zugazagoitia is currently taking a break and because it looks like an issue with [javalin-ssl](https://github.com/javalin/javalin-ssl) & underlying dependencies, this issue is currently on hold. Keep in mind, that like most users, you can (and often should) probably configure SSL in your reverse proxy service like e.g. Nginx, not Reposilite.

**Comment by zugazagoitia** [comment]
Sorry everyone for the delay on this issue, I believe we have found the issue and a fix is on the way!

>  "No Cipher Suite matching '...' is supported"

Regarding this message, there is nothing wrong with it, I'll try to suppress it since it will probably happen on most JVMs.

> Caused by: javax.crypto.BadPaddingException: pad block corrupted

Regarding this exception I can't actually debug without the certificate but I suspect is a problem with the file or encoding itself.

**Comment by dzikoysk** [comment]
The issue with broken connection on HTTP2 should be fixed by excluding from minimize one of Jetty modules:

* https://github.com/javalin/javalin-ssl/issues/59#issuecomment-1422869728

Thanks to @zugazagoitia that helped to diagnose this bug! ❤️
