### ISSUE TITLE
Dashboard auth issues on 2.7.x using Chrome

### ISSUE THREAD

**Issue by dzikoysk** [dzikoysk/reposilite#172]

**Comment by gmax9803** [comment]
This still appears to be an issue, while now I can see the repos, the CLI and uploading do not work. Below is the Chrome console log.

```app.js:7 REPOSILITE_BASE_PATH: /
app.js:7 REPOSILITE_VUE_BASE_PATH: 
app.js:7 REPOSILITE_MESSAGE: Repository dashboard not found
app.js:7 DOMException: Failed to construct 'WebSocket': The subprotocol 'admin:keygoeshere' is invalid.
    at a.created (http://111serverip111/js/app.js:7:132084)
    at ne (http://111serverip111/js/app.js:7:11677)
    at Mn (http://111serverip111/js/app.js:7:29145)
    at a.t._init (http://111serverip111/js/app.js:7:34510)
    at new a (http://111serverip111/js/app.js:7:35770)
    at on (http://111serverip111/js/app.js:7:21670)
    at init (http://111serverip111/js/app.js:7:20536)
    at n (http://111serverip111/js/app.js:7:21872)
    at h (http://111serverip111/js/app.js:7:44201)
    at d (http://111serverip111/js/app.js:7:43830)
ie @ app.js:7
app.js:7 TypeError: Cannot read property 'send' of undefined
    at a.execute (app.js:7)
    at keyup (app.js:7)
    at ne (app.js:7)
    at HTMLInputElement.n (app.js:7)
    at HTMLInputElement.Qi.o._wrapper (app.js:7)
ie @ app.js:7
app.js:7 TypeError: Cannot read property 'send' of undefined
    at a.execute (app.js:7)
    at keyup (app.js:7)
    at ne (app.js:7)
    at HTMLInputElement.n (app.js:7)
    at HTMLInputElement.Qi.o._wrapper (app.js:7)
ie @ app.js:7
```

**Comment by dzikoysk** [comment]
#178
