### ISSUE TITLE
Improve error logging for invalid S3 credentials

### ISSUE THREAD

**Issue by Southpaw1496** [dzikoysk/reposilite#1755]
### What happened?

I tried to set up a new repository connected to an S3 bucket, and the configuration saved correctly, but it did not show up in the repository index on the homepage. On inspecting the logs, it was clear its request had failed (error 400) but this was not shown in the UI. The response body was also not shown, making it more difficult to diagnose the error.

### Reposilite version

3.x

### Relevant log output

```shell
14:43:18.647 ERROR | Cannot load quiltmc repository
14:43:18.649 ERROR | software.amazon.awssdk.services.s3.model.S3Exception: null (Service: S3, Status Code: 400, Request ID: null)
14:43:18.659 ERROR | 	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleErrorResponse(AwsXmlPredicatedResponseHandler.java:156)
14:43:18.660 ERROR | 	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleResponse(AwsXmlPredicatedResponseHandler.java:108)
14:43:18.660 ERROR | 	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:85)
14:43:18.661 ERROR | 	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:43)
14:43:18.662 ERROR | 	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler$Crc32ValidationResponseHandler.handle(AwsSyncClientHandler.java:95)
14:43:18.662 ERROR | 	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$successTransformationResponseHandler$7(BaseClientHandler.java:270)
14:43:18.663 ERROR | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
14:43:18.663 ERROR | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
14:43:18.664 ERROR | 	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
14:43:18.664 ERROR | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
14:43:18.665 ERROR | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
14:43:18.666 ERROR | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
14:43:18.666 ERROR | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
14:43:18.667 ERROR | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
14:43:18.668 ERROR | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
14:43:18.668 ERROR | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
14:43:18.669 ERROR | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
14:43:18.670 ERROR | 	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
14:43:18.671 ERROR | 	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
14:43:18.671 ERROR | 	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
14:43:18.672 ERROR | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
14:43:18.673 ERROR | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
14:43:18.673 ERROR | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
14:43:18.674 ERROR | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
14:43:18.675 ERROR | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
14:43:18.680 ERROR | 	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
14:43:18.681 ERROR | 	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
14:43:18.682 ERROR | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
14:43:18.683 ERROR | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
14:43:18.684 ERROR | 	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
14:43:18.685 ERROR | 	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
14:43:18.685 ERROR | 	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:171)
14:43:18.688 ERROR | 	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
14:43:18.689 ERROR | 	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179)
14:43:18.689 ERROR | 	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
14:43:18.690 ERROR | 	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
14:43:18.691 ERROR | 	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
14:43:18.691 ERROR | 	at software.amazon.awssdk.services.s3.DefaultS3Client.headBucket(DefaultS3Client.java:5249)
14:43:18.692 ERROR | 	at com.reposilite.storage.s3.S3StorageProvider.<init>(S3StorageProvider.kt:67)
14:43:18.697 ERROR | 	at com.reposilite.storage.s3.S3StorageProviderFactory.create(S3StorageProviderFactory.kt:62)
14:43:18.697 ERROR | 	at com.reposilite.storage.s3.S3StorageProviderFactory.create(S3StorageProviderFactory.kt:29)
14:43:18.698 ERROR | 	at com.reposilite.storage.StorageFacade.createStorageProvider(StorageFacade.kt:32)
14:43:18.698 ERROR | 	at com.reposilite.maven.RepositoryFactory.createRepository(RepositoryFactory.kt:47)
14:43:18.699 ERROR | 	at com.reposilite.maven.RepositoryProvider$createRepositories$1.invoke(RepositoryProvider.kt:55)
14:43:18.700 ERROR | 	at com.reposilite.maven.RepositoryProvider$createRepositories$1.invoke(RepositoryProvider.kt:54)
14:43:18.700 ERROR | 	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
14:43:18.701 ERROR | 	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
14:43:18.701 ERROR | 	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
14:43:18.702 ERROR | 	at com.reposilite.maven.RepositoryProvider.createRepositories(RepositoryProvider.kt:72)
14:43:18.702 ERROR | 	at com.reposilite.maven.RepositoryProvider.access$createRepositories(RepositoryProvider.kt:26)
14:43:18.703 ERROR | 	at com.reposilite.maven.RepositoryProvider$1.invoke(RepositoryProvider.kt:39)
14:43:18.704 ERROR | 	at com.reposilite.maven.RepositoryProvider$1.invoke(RepositoryProvider.kt:37)
14:43:18.704 ERROR | 	at com.reposilite.maven.RepositoryProvider._init_$lambda$0(RepositoryProvider.kt:37)
14:43:18.705 ERROR | 	at panda.std.reactive.Reference.lambda$subscribe$1(Reference.java:55)
14:43:18.705 ERROR | 	at panda.std.reactive.Reference.lambda$notifySubscribers$0(Reference.java:50)
14:43:18.706 ERROR | 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
14:43:18.706 ERROR | 	at panda.std.reactive.Reference.notifySubscribers(Reference.java:50)
14:43:18.707 ERROR | 	at panda.std.reactive.Reference.set(Reference.java:45)
14:43:18.707 ERROR | 	at panda.std.reactive.Reference.lambda$computed$3(Reference.java:89)
14:43:18.708 ERROR | 	at panda.std.reactive.Reference.lambda$subscribe$1(Reference.java:55)
14:43:18.709 ERROR | 	at panda.std.reactive.Reference.lambda$notifySubscribers$0(Reference.java:50)
14:43:18.709 ERROR | 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
14:43:18.710 ERROR | 	at panda.std.reactive.Reference.notifySubscribers(Reference.java:50)
14:43:18.710 ERROR | 	at panda.std.reactive.Reference.set(Reference.java:45)
14:43:18.711 ERROR | 	at panda.std.reactive.MutableReference.update(MutableReference.java:29)
14:43:18.711 ERROR | 	at com.reposilite.configuration.shared.SharedConfigurationFacade$1$4.invoke(SharedConfigurationFacade.kt:60)
14:43:18.712 ERROR | 	at com.reposilite.configuration.shared.SharedConfigurationFacade$1$4.invoke(SharedConfigurationFacade.kt:49)
14:43:18.712 ERROR | 	at com.reposilite.configuration.shared.DefaultSharedSettingsReference.update$lambda$0(SharedSettingsReference.kt:51)
14:43:18.713 ERROR | 	at panda.std.Result.supplyThrowing(Result.java:133)
14:43:18.714 ERROR | 	at panda.std.Result.supplyThrowing(Result.java:125)
14:43:18.714 ERROR | 	at com.reposilite.configuration.shared.DefaultSharedSettingsReference.update(SharedSettingsReference.kt:51)
14:43:18.715 ERROR | 	at com.reposilite.configuration.shared.SharedConfigurationFacade.updateSharedSettings(SharedConfigurationFacade.kt:114)
14:43:18.715 ERROR | 	at com.reposilite.configuration.shared.infrastructure.SettingsEndpoints$updateConfiguration$1$1.invoke(SettingsEndpoints.kt:123)
14:43:18.716 ERROR | 	at com.reposilite.configuration.shared.infrastructure.SettingsEndpoints$updateConfiguration$1$1.invoke(SettingsEndpoints.kt:118)
14:43:18.717 ERROR | 	at com.reposilite.shared.ContextDsl$managerOnly$1.invoke$lambda$0(ContextDsl.kt:89)
14:43:18.717 ERROR | 	at panda.std.Result.peek(Result.java:252)
14:43:18.718 ERROR | 	at com.reposilite.shared.ContextDsl$managerOnly$1.invoke(ContextDsl.kt:89)
14:43:18.718 ERROR | 	at com.reposilite.shared.ContextDsl$managerOnly$1.invoke(ContextDsl.kt:87)
14:43:18.719 ERROR | 	at com.reposilite.shared.ContextDsl$authenticated$1.accept(ContextDsl.kt:68)
14:43:18.719 ERROR | 	at com.reposilite.shared.ContextDsl$authenticated$1.accept(ContextDsl.kt:68)
14:43:18.720 ERROR | 	at panda.std.Result.peek(Result.java:252)
14:43:18.721 ERROR | 	at com.reposilite.shared.ContextDsl.authenticated(ContextDsl.kt:68)
14:43:18.721 ERROR | 	at com.reposilite.shared.ContextDsl.managerOnly(ContextDsl.kt:87)
14:43:18.722 ERROR | 	at com.reposilite.configuration.shared.infrastructure.SettingsEndpoints$updateConfiguration$1.invoke(SettingsEndpoints.kt:118)
14:43:18.722 ERROR | 	at com.reposilite.configuration.shared.infrastructure.SettingsEndpoints$updateConfiguration$1.invoke(SettingsEndpoints.kt:117)
14:43:18.723 ERROR | 	at com.reposilite.web.application.JavalinConfiguration$configureRoutingPlugin$reposiliteDsl$1.invoke$lambda$0(JavalinConfiguration.kt:155)
14:43:18.723 ERROR | 	at io.javalin.routing.HandlerEntry.handle(HandlerEntry.kt:19)
14:43:18.724 ERROR | 	at io.javalin.http.servlet.DefaultTasks.HTTP$lambda-8$lambda-6$lambda-5(DefaultTasks.kt:38)
14:43:18.724 ERROR | 	at io.javalin.http.servlet.JavalinServlet.handleTask(JavalinServlet.kt:88)
14:43:18.725 ERROR | 	at io.javalin.http.servlet.JavalinServlet.handleSync(JavalinServlet.kt:53)
14:43:18.726 ERROR | 	at io.javalin.http.servlet.JavalinServlet.service(JavalinServlet.kt:41)
14:43:18.726 ERROR | 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
14:43:18.727 ERROR | 	at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58)
14:43:18.727 ERROR | 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
14:43:18.728 ERROR | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
14:43:18.728 ERROR | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
14:43:18.729 ERROR | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
14:43:18.729 ERROR | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
14:43:18.730 ERROR | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
14:43:18.730 ERROR | 	at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:57)
14:43:18.731 ERROR | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
14:43:18.731 ERROR | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
14:43:18.732 ERROR | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
14:43:18.732 ERROR | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
14:43:18.733 ERROR | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1304)
14:43:18.734 ERROR | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
14:43:18.734 ERROR | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
14:43:18.735 ERROR | 	at org.eclipse.jetty.server.Server.handle(Server.java:563)
14:43:18.735 ERROR | 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
14:43:18.736 ERROR | 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
14:43:18.736 ERROR | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
14:43:18.737 ERROR | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
14:43:18.737 ERROR | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
14:43:18.738 ERROR | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
14:43:18.739 ERROR | 	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
14:43:18.739 ERROR | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:936)
14:43:18.740 ERROR | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1080)
14:43:18.741 ERROR | 	at java.base/java.lang.Thread.run(Thread.java:1589)
```

**Comment by dzikoysk** [comment]
https://github.com/aws/aws-sdk-java-v2/issues/3318

**Comment by dzikoysk** [comment]
I've added extra logging of passed properties to S3 instance, but that's pretty much all I can do for now.
