### ISSUE TITLE
Prometheus plugin don't work after routing refactoring

### ISSUE THREAD

**Issue by enimaloc** [dzikoysk/reposilite#1825]
### What happened?

After installing Prometheus plugin, it show the stacktrace below

### Reposilite version

3.x

### Relevant log output

```shell
12:48:08.146 INFO | Prometheus | Default StatisticsHandler collector has been initialized.
12:48:08.147 INFO | Prometheus | QueuedThreadPool collector has been initialized.
Exception in thread "Reposilite | Main Thread" java.lang.NoClassDefFoundError: io/javalin/community/routing/Route
     at com.reposilite.plugin.prometheus.PrometheusEndpoints.<init>(PrometheusEndpoints.kt:15)
     at com.reposilite.plugin.prometheus.PrometheusPlugin.initialize$lambda$1(PrometheusPlugin.kt:59)
     at com.reposilite.plugin.Extensions.emitEvent(Extensions.kt:66)
     at com.reposilite.web.application.JavalinConfiguration.configureReactiveRoutingPlugin(JavalinConfiguration.kt:130)
     at com.reposilite.web.application.JavalinConfiguration.configure$reposilite_backend(JavalinConfiguration.kt:83)
     at com.reposilite.web.HttpServer.createJavalin$lambda-8(HttpServer.kt:70)
     at io.javalin.config.JavalinConfig$Companion.applyUserConfig(JavalinConfig.kt:42)
     at io.javalin.config.JavalinConfig.applyUserConfig(JavalinConfig.kt)
     at io.javalin.Javalin.create(Javalin.java:93)
     at com.reposilite.web.HttpServer.createJavalin(HttpServer.kt:70)
     at com.reposilite.web.HttpServer.start(HttpServer.kt:46)
     at com.reposilite.Reposilite.launch(Reposilite.kt:64)
     at com.reposilite.ReposiliteLauncherKt.main(ReposiliteLauncher.kt:22)
Caused by: java.lang.ClassNotFoundException: io.javalin.community.routing.Route
     at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
     ... 13 more
```

**Comment by dzikoysk** [comment]
I took a look at the PrometheusPlugin and it looks fine, I think you've used newer version of Prometheus plugin with older version of Reposilite.
