### ISSUE TITLE
Error loading configuration in 2.8.0

### ISSUE THREAD

**Issue by jolheiser** [dzikoysk/reposilite#197]
```
Aug 05 23:52:27 vps590480 java[2472]: 23:52:27.040 INFO |
Aug 05 23:52:27 vps590480 java[2472]: 23:52:27.047 INFO | Reposilite 2.8.0
Aug 05 23:52:27 vps590480 java[2472]: 23:52:27.047 INFO |
Aug 05 23:52:27 vps590480 java[2472]: 23:52:27.067 INFO | Legacy configuration file has been found
Aug 05 23:52:27 vps590480 java[2472]: Exception in thread "main" java.lang.RuntimeException: Cannot load configuration
Aug 05 23:52:27 vps590480 java[2472]:         at org.panda_lang.reposilite.config.ConfigurationLoader.tryLoad(ConfigurationLoader.java:38)
Aug 05 23:52:27 vps590480 java[2472]:         at org.panda_lang.reposilite.Reposilite.<init>(Reposilite.java:74)
Aug 05 23:52:27 vps590480 java[2472]:         at org.panda_lang.reposilite.ReposiliteLauncher.create(ReposiliteLauncher.java:82)
Aug 05 23:52:27 vps590480 java[2472]:         at org.panda_lang.reposilite.ReposiliteLauncher.create(ReposiliteLauncher.java:66)
Aug 05 23:52:27 vps590480 java[2472]:         at org.panda_lang.reposilite.ReposiliteLauncher.main(ReposiliteLauncher.java:50)
Aug 05 23:52:27 vps590480 java[2472]: Caused by: java.lang.UnsupportedOperationException: Missing deserializer for class java.lang.String type
Aug 05 23:52:27 vps590480 java[2472]:         at net.dzikoysk.cdn.CdnDeserializer.deserialize(CdnDeserializer.java:66)
Aug 05 23:52:27 vps590480 java[2472]:         at net.dzikoysk.cdn.CdnDeserializer.deserialize(CdnDeserializer.java:24)
Aug 05 23:52:27 vps590480 java[2472]:         at net.dzikoysk.cdn.CDN.parse(CDN.java:19)
Aug 05 23:52:27 vps590480 java[2472]:         at org.panda_lang.reposilite.config.ConfigurationLoader.createConfiguration(ConfigurationLoader.java:79)
Aug 05 23:52:27 vps590480 java[2472]:         at org.panda_lang.reposilite.config.ConfigurationLoader.load(ConfigurationLoader.java:55)
Aug 05 23:52:27 vps590480 java[2472]:         at org.panda_lang.reposilite.config.ConfigurationLoader.tryLoad(ConfigurationLoader.java:36)
Aug 05 23:52:27 vps590480 java[2472]:         ... 4 more
```

**Comment by dzikoysk** [comment]
Could you run this one? Just rename zip to jar (GitHub does not support upload of jar files)

[reposilite-2.8.0.zip](https://github.com/dzikoysk/reposilite/files/5031543/reposilite-2.8.0.zip)

**Comment by jolheiser** [comment]
I actually already manually converted my `.yml` file to a `.cdn` file and migrated it myself. 😬

**Comment by dzikoysk** [comment]
Well, I'm not able to reproduce it. Do you have any extra properties declared in the configuration?

I've just set up a clean instance of Reposilite with a legacy configuration and it still works, so it requires some extra data

![image](https://user-images.githubusercontent.com/4235722/89471915-95aa3600-d77f-11ea-859a-9246c3cfdf5d.png)

**Comment by dzikoysk** [comment]
Ok, it looks like Linux related bug in CDN

```bash
01:33:50.141 INFO |
01:33:50.144 INFO | Reposilite 2.8.0
01:33:50.144 INFO |
01:33:50.159 INFO | Legacy configuration file has been found
Exception in thread "main" java.lang.RuntimeException: Cannot load configuration
        at org.panda_lang.reposilite.config.ConfigurationLoader.tryLoad(ConfigurationLoader.java:38)
        at org.panda_lang.reposilite.Reposilite.<init>(Reposilite.java:74)
        at org.panda_lang.reposilite.ReposiliteLauncher.create(ReposiliteLauncher.java:82)
        at org.panda_lang.reposilite.ReposiliteLauncher.create(ReposiliteLauncher.java:66)
        at org.panda_lang.reposilite.ReposiliteLauncher.main(ReposiliteLauncher.java:50)
Caused by: java.lang.UnsupportedOperationException: Missing deserializer for interface java.util.List type, value: []. Available deserializers: [class java.lang.String, class java.lang.Double, class java.lang.Boolean, class java.lang.Integer]
        at net.dzikoysk.cdn.CdnDeserializer.deserialize(CdnDeserializer.java:68)
        at net.dzikoysk.cdn.CdnDeserializer.deserialize(CdnDeserializer.java:24)
        at net.dzikoysk.cdn.CDN.parse(CDN.java:19)
        at org.panda_lang.reposilite.config.ConfigurationLoader.createConfiguration(ConfigurationLoader.java:79)
        at org.panda_lang.reposilite.config.ConfigurationLoader.load(ConfigurationLoader.java:55)
        at org.panda_lang.reposilite.config.ConfigurationLoader.tryLoad(ConfigurationLoader.java:36)
        ... 4 more
```
