### ISSUE TITLE
Migrations not working for SQLite?

### ISSUE THREAD

**Issue by felixscheinost** [dzikoysk/reposilite#2019]
### What happened?

I am trying to setup Reposilite using the Helm chart v1.3.2.

I am using a pretty default config, but I added `--enable-migrations` to `REPOSILITE_OPTS`. This leads to the exception below:

### Reposilite version

3.x

### Relevant log output

```shell
Exception in thread "main" java.lang.UnsupportedOperationException: Unsupported SQL dialect SQLite
	at com.reposilite.statistics.infrastructure.SqlStatisticsRepository$runFixes$1.invoke(SqlStatisticsRepository.kt:102)
	at com.reposilite.statistics.infrastructure.SqlStatisticsRepository$runFixes$1.invoke(SqlStatisticsRepository.kt:86)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:275)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:322)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:330)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:321)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:230)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:330)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:200)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:178)
	at com.reposilite.statistics.infrastructure.SqlStatisticsRepository.runFixes(SqlStatisticsRepository.kt:86)
	at com.reposilite.statistics.infrastructure.SqlStatisticsRepository.<init>(SqlStatisticsRepository.kt:80)
	at com.reposilite.statistics.application.StatisticsComponents.statisticsRepository(StatisticsComponents.kt:39)
	at com.reposilite.statistics.application.StatisticsComponents.statisticsFacade$default(StatisticsComponents.kt:42)
	at com.reposilite.statistics.application.StatisticsPlugin.initialize(StatisticsPlugin.kt:45)
	at com.reposilite.statistics.application.StatisticsPlugin.initialize(StatisticsPlugin.kt:34)
	at com.reposilite.plugin.PluginLoader.initialize(PluginLoader.kt:48)
	at com.reposilite.ReposiliteFactory.createReposilite(ReposiliteFactory.kt:87)
	at com.reposilite.ReposiliteFactory.createReposilite(ReposiliteFactory.kt:36)
	at com.reposilite.ReposiliteLauncherKt.createWithParameters(ReposiliteLauncher.kt:41)
	at com.reposilite.ReposiliteLauncherKt.main(ReposiliteLauncher.kt:22)
```

It seems that for some reason `db.vendor` in my case is `SQLite` instead of `sqlite` (what the code expects).

**Comment by dzikoysk** [comment]
Thanks for reporting this - lately, Exposed introduces some breaking changes, so I guess that's one of them. Anyway, it shouldn't be an issue for you, this flag is only used if you're migrating from Reposilite 3.0.x -> 3.1+

**Comment by felixscheinost** [comment]
Ah okay, this was a first time install and I just looked through options which looked like I wanted to turn them on. Thanks!
