### ISSUE TITLE
Reposilite 3.5.7 fails with java.lang.IllegalMonitorStateException

### ISSUE THREAD

**Issue by JWood48** [dzikoysk/reposilite#2072]
### What happened?

I have reposilite running on azure kubernetes. After update to 3.5.7 i get below error in log and reposilite fails to restart

I have downgraded to 3.5.6 and monitoring for issues...

### Reposilite version

3.x

### Relevant log output

```shell
2024-03-06 09:28:21.137		at java.base/java.lang.Thread.run(Thread.java:1583)
2024-03-06 09:28:21.137		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
2024-03-06 09:28:21.137		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
2024-03-06 09:28:21.137		at com.reposilite.storage.filesystem.FileSystemStorageProvider.acquireFileAccessLock$lambda$3$lambda$2$lambda$1(FileSystemStorageProvider.kt:101)
2024-03-06 09:28:21.137		at java.base/java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.unlock(ReentrantReadWriteLock.java:1147)
2024-03-06 09:28:21.137		at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1059)
2024-03-06 09:28:21.137		at java.base/java.util.concurrent.locks.ReentrantReadWriteLock$Sync.tryRelease(ReentrantReadWriteLock.java:372)
2024-03-06 09:28:21.137	Exception in thread "pool-2-thread-13" java.lang.IllegalMonitorStateException
2024-03-06 09:28:21.113		at java.base/java.lang.Thread.run(Thread.java:1583)
2024-03-06 09:28:21.112		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
2024-03-06 09:28:21.112		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
2024-03-06 09:28:21.112		at com.reposilite.storage.filesystem.FileSystemStorageProvider.acquireFileAccessLock$lambda$3$lambda$2$lambda$1(FileSystemStorageProvider.kt:100)
2024-03-06 09:28:21.112		at java.base/java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.unlock(ReentrantReadWriteLock.java:897)
2024-03-06 09:28:21.112		at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.releaseShared(AbstractQueuedSynchronizer.java:1146)
2024-03-06 09:28:21.112		at java.base/java.util.concurrent.locks.ReentrantReadWriteLock$Sync.tryReleaseShared(ReentrantReadWriteLock.java:432)
2024-03-06 09:28:21.112		at java.base/java.util.concurrent.locks.ReentrantReadWriteLock$Sync.unmatchedUnlockException(ReentrantReadWriteLock.java:448)
2024-03-06 09:28:21.112	Exception in thread "pool-2-thread-12" java.lang.IllegalMonitorStateException: attempt to unlock read lock, not locked by current thread
```

**Comment by dzikoysk** [comment]
Thanks for reporting this, we have a new locking mechanism, and it seems to be incorrect. I'll try to take a look at it this week.

**Comment by dzikoysk** [comment]
Hopefully this one will work fine for you:

* https://github.com/dzikoysk/reposilite/releases/tag/3.5.8
