### ISSUE TITLE
Does not detect SSL certificates when using docker

### ISSUE THREAD

**Issue by AlgorithmLX** [dzikoysk/reposilite#2250]
### What happened?

I ran into a problem today when moving a repository to docker. Reposilite does not find the certificate when it is present. I thought I had configured something wrong, but no.

![image](https://github.com/user-attachments/assets/e5cb57f1-917d-41b7-b7b9-d42dc1e1e69f)
![image](https://github.com/user-attachments/assets/b327f203-7e79-4c1e-a75c-6af27cff7403)

### Reposilite version

3.x

### Relevant log output

```shell
07:48:32.370 INFO | + private (private)
07:48:32.370 INFO | 3 repositories have been found
07:48:32.764 INFO | 
07:48:32.763 WARN | Interactive CLI is not available in current environment.
07:48:32.764 WARN | Solution for Docker users: https://docs.docker.com/engine/reference/run/#foreground
07:48:32.765 INFO | Binding server at 0.0.0.0::80
07:48:32.852 INFO | Enabling SSL connector at ::443
07:48:33.121 ERROR | Failed to start Reposilite
07:48:33.124 ERROR | nl.altindag.ssl.exception.GenericIOException: java.nio.file.NoSuchFileException: /etc/letsencrypt/live/maven.0mods.team-0001/fullchain.pem
07:48:33.125 ERROR | 	at nl.altindag.ssl.util.internal.IOUtils.getFileAsStream(IOUtils.java:86)
07:48:33.126 ERROR | 	at nl.altindag.ssl.pem.util.PemUtils.loadIdentityMaterial(PemUtils.java:363)
07:48:33.126 ERROR | 	at nl.altindag.ssl.pem.util.PemUtils.loadIdentityMaterial(PemUtils.java:300)
07:48:33.127 ERROR | 	at io.javalin.community.ssl.SslConfig.pemFromPath(SslConfig.kt:140)
07:48:33.127 ERROR | 	at com.reposilite.web.application.JavalinConfiguration.configureSSL$lambda$6(JavalinConfiguration.kt:147)
07:48:33.128 ERROR | 	at io.javalin.plugin.Plugin.(PluginApi.kt:52)
07:48:33.133 ERROR | 	at io.javalin.community.ssl.SslPlugin.(SslPlugin.kt:24)
07:48:33.136 ERROR | 	at com.reposilite.web.application.JavalinConfiguration.configureSSL(JavalinConfiguration.kt:129)
07:48:33.137 ERROR | 	at com.reposilite.web.application.JavalinConfiguration.configure$reposilite_backend(JavalinConfiguration.kt:70)
07:48:33.138 ERROR | 	at com.reposilite.web.HttpServer.start$lambda$4(HttpServer.kt:48)
07:48:33.138 ERROR | 	at io.javalin.Javalin.lambda$createAndStart$2(Javalin.java:89)
07:48:33.139 ERROR | 	at io.javalin.config.JavalinConfig$Companion.applyUserConfig(JavalinConfig.kt:107)
07:48:33.143 ERROR | 	at io.javalin.config.JavalinConfig.applyUserConfig(JavalinConfig.kt)
07:48:33.144 ERROR | 	at io.javalin.Javalin.create(Javalin.java:73)
07:48:33.145 ERROR | 	at io.javalin.Javalin.createAndStart(Javalin.java:87)
07:48:33.146 ERROR | 	at com.reposilite.web.HttpServer.start(HttpServer.kt:44)
07:48:33.147 ERROR | 	at com.reposilite.Reposilite.launch(Reposilite.kt:64)
07:48:33.147 ERROR | 	at com.reposilite.ReposiliteLauncherKt.main(ReposiliteLauncher.kt:22)
07:48:33.148 ERROR | Caused by: java.nio.file.NoSuchFileException: /etc/letsencrypt/live/maven.0mods.team-0001/fullchain.pem
07:48:33.149 ERROR | 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
07:48:33.149 ERROR | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
07:48:33.150 ERROR | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
07:48:33.150 ERROR | 	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)
07:48:33.150 ERROR | 	at java.base/java.nio.file.Files.newByteChannel(Files.java:379)
07:48:33.151 ERROR | 	at java.base/java.nio.file.Files.newByteChannel(Files.java:431)
07:48:33.151 ERROR | 	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
07:48:33.152 ERROR | 	at java.base/java.nio.file.Files.newInputStream(Files.java:159)
07:48:33.152 ERROR | 	at nl.altindag.ssl.util.internal.IOUtils.getFileAsStream(IOUtils.java:84)
07:48:33.152 ERROR | 	... 17 more
07:48:33.153 ERROR | 
07:48:33.154 INFO | Shutting down 0.0.0.0::80...
reposilite:x:999:999::/nonexistent:/bin/sh
```

**Comment by AlgorithmLX** [comment]
well.. i tried a different path, it doesn't work.
![image](https://github.com/user-attachments/assets/5c1e8ead-f8c4-4874-a6fe-c33d43caee72)
![image](https://github.com/user-attachments/assets/85582351-0381-470a-adda-2f6609c8ebf7)

**Comment by solonovamax** [comment]
well yeah.. you didn't mount the file in docker, so obviously docker can't see it

**Comment by dzikoysk** [comment]
Hey, sorry for late response - I just missed the notification. I'd also personally recommend to just not use the built-in SSL integration, it's good enough to setup it at the proxy level (like Nginx) for all your services.

**Comment by AlgorithmLX** [comment]
> well yeah.. you didn't mount the file in docker, so obviously docker can't see it

i actually mounted the file. and i gave it full access, otherwise it wouldn't be displayed in the docker system.

**Comment by AlgorithmLX** [comment]
> Hey, sorry for late response - I just missed the notification. I'd also personally recommend to just not use the built-in SSL integration, it's good enough to setup it at the proxy level (like Nginx) for all your services. 
Хм.. попробую

**Comment by AlgorithmLX** [comment]
> Hey, sorry for late response - I just missed the notification. I'd also personally recommend to just not use the built-in SSL integration, it's good enough to setup it at the proxy level (like Nginx) for all your services. 

hmm... i'll try it.

**Comment by solonovamax** [comment]
> > well yeah.. you didn't mount the file in docker, so obviously docker can't see it
> 
> i actually mounted the file. and i gave it full access, otherwise it wouldn't be displayed in the docker system.

oops, didn't notice that lol
