### ISSUE TITLE
Potential storage issue under Windows

### ISSUE THREAD

**Issue by sgebbie** [dzikoysk/reposilite#264]
It looks like 03d5e32b6630b246d19bd9a75c7b2c2409f22739 may have caused a storage issue with running Reposilite under under Windows.

This was from a local built off of: eede3765864884eb07018854bd47c87b0bdf7a9f.

I was not receiving this error when running the binary release of 2.8.5.

Unfortunately I have not looked into the issue, but I wonder if it might be related to concurrent file access, which can be problematic under Windows if another thread or process still has the file open when it is being deleted (in order to be replaced).

```
11:46:32.361 ERROR | releases/com/github/node-gradle/node/com.github.node-gradle.node.gradle.plugin/2.2.3/com.github.node-gradle.node.gradle.plugin-2.2.3.pom.sha1: java.nio.file.AccessDeniedException: .\repositories\releases\com\github\node-gradle\node\com.github.node-gradl
11:46:23.401 ERROR | releases/com/github/node-gradle/node/com.github.node-gradle.node.gradle.plugin/2.2.3/com.github.node-gradle.node.gra
dle.plugin-2.2.3.pom: java.nio.file.AccessDeniedException: .\repositories\releases\com\github\node-gradle\node\com.github.node-gradle.nod
e.gradle.plugin\2.2.3\com.github.node-gradle.node.gradle.plugin-2.2.3.pom
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
        at java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
        at java.nio.file.Files.newOutputStream(Unknown Source)
        at java.nio.file.Files.copy(Unknown Source)
        at org.panda_lang.reposilite.repository.RepositoryStorage.storeFileSync(RepositoryStorage.java:96)
        at org.panda_lang.reposilite.repository.RepositoryService.lambda$storeFile$0(RepositoryService.java:64)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by dzikoysk** [comment]
Reposilite 2.8.5 is the latest stable version and you should use it to avoid such a problems for now :) Current changes on master are not stable yet (#258), but thanks for reporting this issue!

**Comment by dzikoysk** [comment]
@sgebbie If you want to still help in the development process, could you tell me if the problem still occur? :) 

![image](https://user-images.githubusercontent.com/4235722/94006009-769f4c00-fd9f-11ea-99b9-35d2fc4a489e.png)

The `reposilite-test` artifact seems to look fine.

**Comment by sgebbie** [comment]
Firstly, thanks for the quick response.

I've built 2aa6fff and tried using it from a simple Gradle build (just running `gradle clean`). I'm not seeing the access denied errors anymore, but I am seeing some other issues now. I've attached a copy of the logs:

[reposilite-2.8.5.built.2aa6fff.jar.log.txt](https://github.com/dzikoysk/reposilite/files/5268046/reposilite-2.8.5.built.2aa6fff.jar.log.txt)

**Comment by dzikoysk** [comment]
Thanks! Well I think I'll replace these strange file locking api with just a simple extension .`lock` based mechanism
