### ISSUE TITLE
Manually uploaded files dont show up on the website

### ISSUE THREAD

**Issue by DeadlyMC** [dzikoysk/reposilite#355]
We are in the process of moving our files from bintray to our new reposilite maven, but manually uploading the files doesnt seem to work. The files dont show up on the repo, it says the directory is empty.
![image](https://user-images.githubusercontent.com/43000902/107179732-462e1680-69fd-11eb-8738-66c79a441e6c.png)
Whereas if you check the file directory from winscp, the files are indeed present.
![image](https://user-images.githubusercontent.com/43000902/107179780-61992180-69fd-11eb-97bc-094f8b5c2405.png)

**Comment by DeadlyMC** [comment]
Oh and we tried changing the file permissions to 0770 (rwxrwx---), but that didnt help too
![image](https://user-images.githubusercontent.com/43000902/107179935-b5a40600-69fd-11eb-9e87-ddbc61245212.png)

The files pushed by gradle have the 0770 permission and they are visible on the website too

**Comment by dzikoysk** [comment]
You have a typical symptom of CDN caching. Look here:

![image](https://user-images.githubusercontent.com/4235722/107218878-8945b500-6a10-11eb-9c20-95579dbc4d86.png)

Reposilite doesn't store information about artifacts in memory, so it's just impossible to not detect changes on disk.

**Comment by BluCobalt** [comment]
![image](https://user-images.githubusercontent.com/37788256/107300847-1e57a680-6a2f-11eb-8fca-7adff07636c6.png)
As seen here when cloudflare is bypassed and a connection to reposilite is directly made the directory is still not listed

**Comment by dzikoysk** [comment]
I can confirm it is probably a bug. It seems like these requests:

* https://maven.legacyfabric.net/api/releases/net/fabricmc/fabric-loader-1.8.9 (empty response)
* https://maven.legacyfabric.net/releases/net/fabricmc/fabric-loader-1.8.9/latest (probably throwing exception?)

Do you have any exception in console? I think it might be connected with custom build names/content of these directories. 
If you could share me the content of `fabric-loader-1.8.9` directory, I could try to reproduce this bug.

**Comment by DeadlyMC** [comment]
[fabric-loader-1.8.9.zip](https://github.com/dzikoysk/reposilite/files/5949014/fabric-loader-1.8.9.zip)
@dzikoysk There

**Comment by BluCobalt** [comment]
> Do you have any exception in console? I think it might be connected with custom build names/content of these directories.
It looks like it is.
```
21:53:23.025 ERROR | /api/releases/net/fabricmc/fabric-loader-1.8.9/: java.lang.NumberFormatException: For input string: "202004210808"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at org.panda_lang.reposilite.metadata.MetadataComparator.compare(MetadataComparator.java:58)
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.base/java.util.TimSort.sort(TimSort.java:220)
	at java.base/java.util.Arrays.sort(Arrays.java:1515)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:353)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.panda_lang.utilities.commons.function.PandaStream.toList(PandaStream.java:139)
	at org.panda_lang.reposilite.repository.LookupApiEndpoint.handleContext(LookupApiEndpoint.java:95)
	at org.panda_lang.reposilite.RepositoryController.handle(RepositoryController.java:27)
	at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:23)
	at io.javalin.http.JavalinServlet$addHandler$protectedHandler$1.handle(JavalinServlet.kt:121)
	at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:45)
	at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:24)
	at io.javalin.http.JavalinServlet$service$1.invoke(JavalinServlet.kt:129)
	at io.javalin.http.JavalinServlet$service$2.invoke(JavalinServlet.kt:40)
	at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:81)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.javalin.websocket.JavalinWsServlet.service(JavalinWsServlet.kt:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at io.javalin.core.JavalinServer$start$wsAndHttpHandler$1.doHandle(JavalinServer.kt:49)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by dzikoysk** [comment]
2.9.12 should work fine:

* https://repo.panda-lang.org/org/panda-lang/reposilite/2.9.12/reposilite-2.9.12.jar

**Comment by BluCobalt** [comment]
This works, thank you!
