### ISSUE TITLE
Cannot deploy jar with Kotlin DSL

### ISSUE THREAD

**Issue by milkyway0308** [dzikoysk/reposilite#412]
Deploy keep failed when upload jar file without log, but pom is uploaded.

Kotlin DSL Code
```
publishing {
    println(project.properties.keys)
    println(System.getProperties().keys)
    repositories {
        maven {
            name = "Reposilite"
            url = uri(properties["reposilite.release"] as String)
            credentials {
                username = properties["reposilite.user"] as String
                password = properties["reposilite.token"] as String
            }
            authentication {
                create<BasicAuthentication>("basic")
            }
        }
    }
    publications {
        create<MavenPublication>("jar") {
            from(components["java"])
            groupId = "skywolf46"
            artifactId = "exutil"
            version = properties["version"] as String
        }
    }
}

```

IDE Error
```
Caused by: org.gradle.api.resources.ResourceException: Could not write to resource 'http://repository.skywolf.kr/releases/skywolf46/exutil/1.35.1/exutil-1.35.1.jar'.
	at org.gradle.internal.resource.ResourceExceptions.failure(ResourceExceptions.java:74)
	at org.gradle.internal.resource.ResourceExceptions.putFailed(ResourceExceptions.java:61)
	at org.gradle.internal.resource.transfer.AccessorBackedExternalResource.put(AccessorBackedExternalResource.java:185)
	at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator$3.call(BuildOperationFiringExternalResourceDecorator.java:100)
	at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator$3.call(BuildOperationFiringExternalResourceDecorator.java:97)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator.put(BuildOperationFiringExternalResourceDecorator.java:97)
	at org.gradle.api.publication.maven.internal.wagon.RepositoryTransportWagonAdapter.putRemoteFile(RepositoryTransportWagonAdapter.java:44)
	at org.gradle.api.publication.maven.internal.wagon.RepositoryTransportDeployWagon.put(RepositoryTransportDeployWagon.java:94)
	... 107 more
Caused by: java.net.SocketException: Connection reset by peer: socket write error
	at org.apache.http.impl.io.SessionOutputBufferImpl.streamWrite(SessionOutputBufferImpl.java:124)
	at org.apache.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:136)
	at org.apache.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:167)
	at org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:113)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2315)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2270)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2291)
	at org.gradle.internal.resource.transport.http.RepeatableInputStreamEntity.writeTo(RepeatableInputStreamEntity.java:55)
	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156)
	at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:160)
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performHttpRequest(HttpClientHelper.java:132)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performHttpRequest(HttpClientHelper.java:113)
	at org.gradle.internal.resource.transport.http.HttpResourceUploader.upload(HttpResourceUploader.java:39)
	at org.gradle.internal.resource.transfer.DefaultExternalResourceConnector.upload(DefaultExternalResourceConnector.java:76)
	at org.gradle.internal.resource.transfer.ProgressLoggingExternalResourceUploader.upload(ProgressLoggingExternalResourceUploader.java:39)
	at org.gradle.internal.resource.transfer.AccessorBackedExternalResource.put(AccessorBackedExternalResource.java:182)
```

Reposilite log
```
06:04:23.207 INFO | DEPLOY /releases/skywolf46/exutil/1.35.1/exutil-1.35.1.pom from x.x.x.x
06:04:23.266 INFO | AUTH skywolf46 accessed /releases/skywolf46/exutil/1.35.1/exutil-1.35.1.pom
06:04:23.266 INFO | DEPLOY skywolf46 successfully deployed ./repositories/releases/skywolf46/exutil/1.35.1/exutil-1.35.1.pom from x.x.x.x
06:04:23.495 INFO | DEPLOY /releases/skywolf46/exutil/1.35.1/exutil-1.35.1.pom.sha1 from x.x.x.x
06:04:23.553 INFO | AUTH skywolf46 accessed /releases/skywolf46/exutil/1.35.1/exutil-1.35.1.pom.sha1
06:04:23.553 INFO | DEPLOY skywolf46 successfully deployed ./repositories/releases/skywolf46/exutil/1.35.1/exutil-1.35.1.pom.sha1 from x.x.x.x
06:04:23.736 INFO | DEPLOY /releases/skywolf46/exutil/1.35.1/exutil-1.35.1.pom.md5 from x.x.x.x
06:04:23.795 INFO | AUTH skywolf46 accessed /releases/skywolf46/exutil/1.35.1/exutil-1.35.1.pom.md5
06:04:23.795 INFO | DEPLOY skywolf46 successfully deployed ./repositories/releases/skywolf46/exutil/1.35.1/exutil-1.35.1.pom.md5 from x.x.x.x```

**Comment by milkyway0308** [comment]
Fixed; It happens when deploy though Cloudflare proxy.
