### ISSUE TITLE
How do I create a valid keystore.jks?

### ISSUE THREAD

**Issue by Protonull** [dzikoysk/reposilite#496]
There's very, *very* little information about this part of the config:
```yml
# Support encrypted connections
sslEnabled: true
# SSL port to bind
sslPort: 443
# Key store file to use.
# You can specify absolute path to the given file or use ${WORKING_DIRECTORY} variable.
keyStorePath: ${WORKING_DIRECTORY}/keystore.jks
# Key store password to use
keyStorePassword: reposilite
# Redirect http traffic to https
enforceSsl: false
```
..most notably the `keystore.jks` part. I assume it has something to do with SSL certificates since this is the SSL section of the config, but my provider didn't give me any `.jks` files, only a `.crt` and `.ca-bundle` file. I have since tried [this guide](http://testingfreak.com/convert-der-crt-p12-jks-file-create-jks-file-using-keytool/) and [this guide](https://docs.oracle.com/cd/E19509-01/820-3503/ggfen/index.html) and neither are helpful since I'm still getting:
```
02:46:26.636 INFO | --- Loading domain configurations
02:46:26.736 INFO | Binding server at 0.0.0.0::80
02:46:26.869 INFO | Enabling SSL connector at ::443
02:46:27.626 ERROR | Failed to start Javalin
02:46:27.628 ERROR | Exception occurred during the task execution: java.lang.RuntimeException: java.io.IOException: Invalid keystore format
        at io.javalin.Javalin.start(Javalin.java:191)
        at io.javalin.Javalin.start(Javalin.java:153)
        at io.javalin.Javalin.start(Javalin.java:140)
        at org.panda_lang.reposilite.ReposiliteHttpServer.start(ReposiliteHttpServer.java:93)
        at org.panda_lang.reposilite.Reposilite.start(Reposilite.java:167)
        at org.panda_lang.reposilite.Reposilite.launch(Reposilite.java:130)
        at org.panda_lang.reposilite.utils.RunUtils.run(RunUtils.java:38)
        at org.panda_lang.reposilite.utils.RunUtils.lambda$ofChecked$0(RunUtils.java:29)
        at org.panda_lang.reposilite.ReposiliteLauncher.lambda$main$0(ReposiliteLauncher.java:48)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at org.panda_lang.reposilite.ReposiliteLauncher.main(ReposiliteLauncher.java:48)
Caused by: java.io.IOException: Invalid keystore format
        at java.base/sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:667)
        at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:222)
        at java.base/java.security.KeyStore.load(KeyStore.java:1479)
        at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:54)
        at org.eclipse.jetty.util.ssl.SslContextFactory.loadKeyStore(SslContextFactory.java:1197)
        at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:321)
        at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:243)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:97)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:321)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.server.Server.doStart(Server.java:401)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at io.javalin.core.JavalinServer.start(JavalinServer.kt:63)
        at io.javalin.Javalin.start(Javalin.java:177)
        ... 10 more
```
And so I am really stuck on what it is I should be doing here since there's precious little information at all on what a valid keystore is. Support for SSL was mentioned [here](https://github.com/dzikoysk/reposilite/issues/288#issuecomment-716838249) but no additional information was given, so are keystores widely known or something?

**Comment by dzikoysk** [comment]
Hi there! Yes, JKS stands for Java KeyStore format. In most cases people does not really use SSL directly in Reposilite, because they serve it behind some proxy services like Nginx anyway. 
The `keystore.jks` is just the most popular name of jks files that `keytool` generates. You may find various resources related to this topic, e.g. on Jenkov's blog or in :

* http://tutorials.jenkov.com/java-cryptography/keytool.html
* https://github.com/tipsy/javalin-http2-example
