### ISSUE TITLE
Move away from openjdk alpine docker image to be able to deploy on arm64 systems

### ISSUE THREAD

**Issue by Minecraftschurli** [dzikoysk/reposilite#558]
the openjdk:<version>-alpine images only support amd64 which makes it impossible to deploy reposilite on arm64 systems (like a raspberrypi 4) so it would be nice if you could replace it with another image (like openjdk:<version>-slim)

**Comment by dzikoysk** [comment]
Tbh I don't know the difference between alpine and slim releases, I use alpine as it's recommended image. I've seen that ARM64 users in fact uses the slim release:

* https://github.com/dzikoysk/reposilite/issues/516#issuecomment-859168689

Does it delivers the same packages for every platform?

**Comment by Minecraftschurli** [comment]
well the slim images are based on debian so it uses the apt package manager instead of alpines apk but there should not be a difference between arm64 and amd64

**Comment by dzikoysk** [comment]
Do you want to make a PR? I think we could apply it to the `master` and `3.0` branches. If not, I'll take care of it during the release phase of 3.x version.

**Comment by Minecraftschurli** [comment]
I tried it on the master branch and it failed with an error in while running the tests. I am currently trying it on 3.0

**Comment by dzikoysk** [comment]
Master branch contains latest stable version of 2.x and it shouldn't fail. Could you try to paste the tests with errors? 🤔 Speaking of the 3.0, it's obviously still not finished, so the final jar won't work yet anyway.

**Comment by Minecraftschurli** [comment]
This is the log of the error when building 2.9.24 on arm64
```log
#15 362.5 [INFO]
#15 362.5 [INFO] -------------------------------------------------------
#15 362.5 [INFO]  T E S T S
#15 362.5 [INFO] -------------------------------------------------------
#15 363.1 [INFO]
#15 363.1 [INFO] Results:
#15 363.1 [INFO]
#15 363.1 [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
#15 363.1 [INFO]
#15 363.2 [INFO] ------------------------------------------------------------------------
#15 363.2 [INFO] Reactor Summary for reposilite-parent 2.9.24:
#15 363.2 [INFO]
#15 363.2 [INFO] reposilite-parent .................................. SUCCESS [ 43.425 s]
#15 363.2 [INFO] reposilite-backend ................................. FAILURE [05:01 min]
#15 363.2 [INFO] ------------------------------------------------------------------------
#15 363.2 [INFO] BUILD FAILURE
#15 363.2 [INFO] ------------------------------------------------------------------------
#15 363.2 [INFO] Total time:  05:49 min
#15 363.2 [INFO] Finished at: 2021-08-29T17:33:39Z
#15 363.2 [INFO] ------------------------------------------------------------------------
#15 363.3 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project reposilite: There are test failures.
#15 363.3 [ERROR]
#15 363.3 [ERROR] Please refer to /app/reposilite-backend/target/surefire-reports for the individual test results.
#15 363.3 [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
#15 363.3 [ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
#15 363.3 [ERROR] Command was /bin/sh -c cd /app/reposilite-backend && /usr/local/openjdk-16/bin/java '-javaagent:/root/.m2/repository/org/jacoco/org.jacoco.agent/0.8.7/org.jacoco.agent-0.8.7-runtime.jar=destfile=/app/reposilite-backend/target/jacoco.exec,excludes=META-INF/**' -jar /app/reposilite-backend/target/surefire/surefirebooter8899376393459912545.jar /app/reposilite-backend/target/surefire 2021-08-29T17-33-33_047-jvmRun1 surefire10281502758653248246tmp surefire_015008654375234185117tmp
#15 363.3 [ERROR]
#15 363.3 [ERROR] Error while executing forked tests.Error while executing process.Cannot run program "/bin/sh" (in directory "/app/reposilite-backend"): error=0, Failed to exec spawn helper: pid: 195, exit value: 1org.apache.maven.surefire.shade.org.apache.maven.shared.utils.cli.CommandLineException: Error while executing process.
#15 363.3 [ERROR]       at org.apache.maven.surefire.shade.org.apache.maven.shared.utils.cli.Commandline.execute(Commandline.java:412)
#15 363.3 [ERROR]       at org.apache.maven.plugin.surefire.booterclient.lazytestprovider.OutputStreamFlushableCommandline.execute(OutputStreamFlushableCommandline.java:65)
#15 363.3 [ERROR]       at org.apache.maven.surefire.shade.org.apache.maven.shared.utils.cli.CommandLineUtils.executeCommandLineAsCallable(CommandLineUtils.java:229)
#15 363.3 [ERROR]       at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:609)
#15 363.3 [ERROR]       at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
#15 363.3 [ERROR]       at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
#15 363.3 [ERROR]       at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
#15 363.3 [ERROR]       at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
#15 363.3 [ERROR]       at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
#15 363.3 [ERROR]       at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
#15 363.3 [ERROR]       at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
#15 363.3 [ERROR]       at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
#15 363.3 [ERROR]       at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
#15 363.3 [ERROR]       at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
#15 363.3 [ERROR]       at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
#15 363.3 [ERROR]       at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
#15 363.3 [ERROR]       at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
#15 363.3 [ERROR]       at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
#15 363.3 [ERROR]       at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
#15 363.3 [ERROR]       at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
#15 363.3 [ERROR]       at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
#15 363.3 [ERROR]       at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
#15 363.4 [ERROR]       at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
#15 363.4 [ERROR]       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#15 363.4 [ERROR]       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
#15 363.4 [ERROR]       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#15 363.4 [ERROR]       at java.base/java.lang.reflect.Method.invoke(Method.java:567)
#15 363.4 [ERROR]       at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
#15 363.4 [ERROR]       at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
#15 363.4 [ERROR]       at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
#15 363.4 [ERROR]       at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
#15 363.4 [ERROR] Caused by: java.io.IOException: Cannot run program "/bin/sh" (in directory "/app/reposilite-backend"): error=0, Failed to exec spawn helper: pid: 195, exit value: 1
#15 363.4 [ERROR]       at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
#15 363.4 [ERROR]       at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
#15 363.4 [ERROR]       at java.base/java.lang.Runtime.exec(Runtime.java:590)
#15 363.4 [ERROR]       at org.apache.maven.surefire.shade.org.apache.maven.shared.utils.cli.Commandline.execute(Commandline.java:407)
#15 363.4 [ERROR]       ... 30 more
#15 363.4 [ERROR] Caused by: java.io.IOException: error=0, Failed to exec spawn helper: pid: 195, exit value: 1
#15 363.4 [ERROR]       at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
#15 363.4 [ERROR]       at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313)
#15 363.4 [ERROR]       at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
#15 363.4 [ERROR]       at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
#15 363.4 [ERROR]       ... 33 more
#15 363.4 [ERROR] Fatal Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Flakes: 0, Elapsed timeout: false
#15 363.4 [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
#15 363.4 [ERROR] Command was /bin/sh -c cd /app/reposilite-backend && /usr/local/openjdk-16/bin/java '-javaagent:/root/.m2/repository/org/jacoco/org.jacoco.agent/0.8.7/org.jacoco.agent-0.8.7-runtime.jar=destfile=/app/reposilite-backend/target/jacoco.exec,excludes=META-INF/**' -jar /app/reposilite-backend/target/surefire/surefirebooter8899376393459912545.jar /app/reposilite-backend/target/surefire 2021-08-29T17-33-33_047-jvmRun1 surefire10281502758653248246tmp surefire_015008654375234185117tmp
#15 363.4 [ERROR]
#15 363.4 [ERROR] Error while executing forked tests.Error while executing process.Cannot run program "/bin/sh" (in directory "/app/reposilite-backend"): error=0, Failed to exec spawn helper: pid: 195, exit value: 1org.apache.maven.surefire.shade.org.apache.maven.shared.utils.cli.CommandLineException: Error while executing process.
#15 363.4 [ERROR]       at org.apache.maven.surefire.shade.org.apache.maven.shared.utils.cli.Commandline.execute(Commandline.java:412)
#15 363.4 [ERROR]       at org.apache.maven.plugin.surefire.booterclient.lazytestprovider.OutputStreamFlushableCommandline.execute(OutputStreamFlushableCommandline.java:65)
#15 363.4 [ERROR]       at org.apache.maven.surefire.shade.org.apache.maven.shared.utils.cli.CommandLineUtils.executeCommandLineAsCallable(CommandLineUtils.java:229)
#15 363.4 [ERROR]       at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:609)
#15 363.4 [ERROR]       at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
#15 363.4 [ERROR]       at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
#15 363.4 [ERROR]       at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
#15 363.4 [ERROR]       at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
#15 363.4 [ERROR]       at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
#15 363.5 [ERROR]       at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
#15 363.5 [ERROR]       at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
#15 363.5 [ERROR]       at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
#15 363.5 [ERROR]       at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
#15 363.5 [ERROR]       at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
#15 363.5 [ERROR]       at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
#15 363.5 [ERROR]       at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
#15 363.5 [ERROR]       at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
#15 363.5 [ERROR]       at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
#15 363.5 [ERROR]       at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
#15 363.5 [ERROR]       at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
#15 363.5 [ERROR]       at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
#15 363.5 [ERROR]       at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
#15 363.5 [ERROR]       at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
#15 363.5 [ERROR]       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#15 363.5 [ERROR]       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
#15 363.5 [ERROR]       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#15 363.5 [ERROR]       at java.base/java.lang.reflect.Method.invoke(Method.java:567)
#15 363.5 [ERROR]       at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
#15 363.5 [ERROR]       at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
#15 363.5 [ERROR]       at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
#15 363.5 [ERROR]       at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
#15 363.5 [ERROR] Caused by: java.io.IOException: Cannot run program "/bin/sh" (in directory "/app/reposilite-backend"): error=0, Failed to exec spawn helper: pid: 195, exit value: 1
#15 363.5 [ERROR]       at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
#15 363.5 [ERROR]       at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
#15 363.5 [ERROR]       at java.base/java.lang.Runtime.exec(Runtime.java:590)
#15 363.5 [ERROR]       at org.apache.maven.surefire.shade.org.apache.maven.shared.utils.cli.Commandline.execute(Commandline.java:407)
#15 363.5 [ERROR]       ... 30 more
#15 363.5 [ERROR] Caused by: java.io.IOException: error=0, Failed to exec spawn helper: pid: 195, exit value: 1
#15 363.5 [ERROR]       at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
#15 363.5 [ERROR]       at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313)
#15 363.5 [ERROR]       at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
#15 363.5 [ERROR]       at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
#15 363.5 [ERROR]       ... 33 more
#15 363.5 [ERROR] Fatal Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Flakes: 0, Elapsed timeout: false
#15 363.6 [ERROR]       at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:669)
#15 363.6 [ERROR]       at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
#15 363.6 [ERROR]       at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
#15 363.6 [ERROR]       at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
#15 363.6 [ERROR]       at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
#15 363.6 [ERROR]       at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
#15 363.6 [ERROR]       at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
#15 363.6 [ERROR]       at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
#15 363.6 [ERROR]       at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
#15 363.6 [ERROR]       at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
#15 363.6 [ERROR]       at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
#15 363.6 [ERROR]       at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
#15 363.6 [ERROR]       at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
#15 363.6 [ERROR]       at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
#15 363.6 [ERROR]       at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
#15 363.6 [ERROR]       at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
#15 363.6 [ERROR]       at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
#15 363.6 [ERROR]       at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
#15 363.6 [ERROR]       at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
#15 363.6 [ERROR]       at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
#15 363.6 [ERROR]       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#15 363.6 [ERROR]       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
#15 363.6 [ERROR]       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#15 363.6 [ERROR]       at java.base/java.lang.reflect.Method.invoke(Method.java:567)
#15 363.6 [ERROR]       at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
#15 363.6 [ERROR]       at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
#15 363.6 [ERROR]       at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
#15 363.7 [ERROR]       at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
#15 363.7 [ERROR] Caused by: java.io.IOException: Cannot run program "/bin/sh" (in directory "/app/reposilite-backend"): error=0, Failed to exec spawn helper: pid: 195, exit value: 1
#15 363.7 [ERROR]       at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
#15 363.7 [ERROR]       at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
#15 363.7 [ERROR]       at java.base/java.lang.Runtime.exec(Runtime.java:590)
#15 363.7 [ERROR]       at org.apache.maven.surefire.shade.org.apache.maven.shared.utils.cli.Commandline.execute(Commandline.java:407)
#15 363.7 [ERROR]       at org.apache.maven.plugin.surefire.booterclient.lazytestprovider.OutputStreamFlushableCommandline.execute(OutputStreamFlushableCommandline.java:65)
#15 363.7 [ERROR]       at org.apache.maven.surefire.shade.org.apache.maven.shared.utils.cli.CommandLineUtils.executeCommandLineAsCallable(CommandLineUtils.java:229)
#15 363.7 [ERROR]       at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:609)
#15 363.7 [ERROR]       ... 27 more
#15 363.7 [ERROR] Caused by: java.io.IOException: error=0, Failed to exec spawn helper: pid: 195, exit value: 1
#15 363.7 [ERROR]       at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
#15 363.7 [ERROR]       at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313)
#15 363.7 [ERROR]       at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
#15 363.7 [ERROR]       at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
#15 363.7 [ERROR]       ... 33 more
#15 363.7 [ERROR]
#15 363.7 [ERROR] -> [Help 1]
#15 363.7 [ERROR]
#15 363.7 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
#15 363.7 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
#15 363.7 [ERROR]
#15 363.7 [ERROR] For more information about the errors and possible solutions, please read the following articles:
#15 363.7 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
#15 363.7 [ERROR]
#15 363.7 [ERROR] After correcting the problems, you can resume the build with the command
#15 363.7 [ERROR]   mvn <args> -rf :reposilite
```

**Comment by Minecraftschurli** [comment]
I think it's a problem with the shade plugin

**Comment by dzikoysk** [comment]
It's a problem with a test runner:

```
#15 363.3 [ERROR] Command was /bin/sh -c cd /app/reposilite-backend && /usr/local/openjdk-16/bin/java '-javaagent:/root/.m2/repository/org/jacoco/org.jacoco.agent/0.8.7/org.jacoco.agent-0.8.7-runtime.jar=destfile=/app/reposilite-backend/target/jacoco.exec,excludes=META-INF/**' -jar /app/reposilite-backend/target/surefire/surefirebooter8899376393459912545.jar /app/reposilite-backend/target/surefire 2021-08-29T17-33-33_047-jvmRun1 surefire10281502758653248246tmp surefire_015008654375234185117tmp
```

Sunfire plugin launches a new JDK instance with JaCoCo plugin to enable tests coverage tracing. Looks like a shell command is not available in this image `"/bin/sh"` 🤔

**Comment by dzikoysk** [comment]
Wait, the build phase currently uses slim version:

https://github.com/dzikoysk/reposilite/blob/c93619ee0626f15bbb1d1b2a3b9e3df6fa433e37/Dockerfile#L2

So it doesn't make sense 🤔

**Comment by Minecraftschurli** [comment]
I got it to work by building it locally and change the COPY to use the local jar instead of the build stage
(but I found out that I can't access the swagger when using a base path and having it behind a reverse proxy)

**Comment by dzikoysk** [comment]
Swagger UI on 2.x is kinda broken in latest releases, but you can still access docs through `/swagger-docs` route.

**Comment by Minecraftschurli** [comment]
> Swagger UI on 2.x is kinda broken in latest releases, but you can still access docs through `/swagger-docs` route.

well then petstore it is 😄

> Yeah, but in official releases it's quite important to build whole app with Docker image to make sure that the Docker based build passes all the tests and delivers expected functionalities.

well since it uses the same base image (just for a different arch) and you cant use a different arch for build and run stage and there is the error with the test runner on arm64 it's the only way I can think of
In production you could use a github action to build and test and then make the image

**Comment by Minecraftschurli** [comment]
the generated openapi docs from `/swagger-docs` don't respect the base path either

**Comment by dzikoysk** [comment]
I don't know to be honest, Gradle process just dies on arm64 platform without any specific message:

```
 #12 [build 4/4] RUN gradle shadowJar --no-daemon --stacktrace
#12 6.294 
#12 6.297 Welcome to Gradle 7.2!
#12 6.299 
#12 6.301 Here are the highlights of this release:
#12 6.305  - Toolchain support for Scala
#12 6.314  - More cache hits when Java source files have platform-specific line endings
#12 6.321  - More resilient remote HTTP build cache behavior
#12 6.322 
#12 6.324 For more details see https://docs.gradle.org/7.2/release-notes.html
#12 6.324 
#12 7.700 To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.2/userguide/gradle_daemon.html#sec:disabling_the_daemon.
#12 8.481 
#12 8.482 FAILURE: Build failed with an exception.
#12 8.485 
#12 8.486 * What went wrong:
#12 8.514 A problem occurred starting process 'Gradle build daemon'
#12 8.515 
#12 8.515 * Try:
#12 8.515 Run with --info or --debug option to get more log output. Run with --scan to get full insights.
#12 8.517 
#12 8.517 * Exception is:
#12 8.517 org.gradle.process.internal.ExecException: A problem occurred starting process 'Gradle build daemon'
#12 8.518 	at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:241)
#12 8.518 	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:218)
#12 8.518 	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:369)
#12 8.519 	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:87)
#12 8.519 	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:38)
#12 8.519 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
#12 8.520 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
#12 8.521 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
#12 8.521 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
#12 8.521 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
#12 8.521 	at java.base/java.lang.Thread.run(Thread.java:831)
#12 8.522 Caused by: net.rubygrapefruit.platform.NativeException: Could not start '/opt/java/openjdk/bin/java'
#12 8.522 	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
#12 8.523 	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
#12 8.523 	at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:98)
#12 8.523 	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:71)
#12 8.524 	... 7 more
#12 8.524 Caused by: java.io.IOException: Cannot run program "/opt/java/openjdk/bin/java" (in directory "/home/gradle/.gradle/daemon/7.2"): error=0, Failed to exec spawn helper: pid: 62, exit value: 1
#12 8.524 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
#12 8.525 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
#12 8.525 	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
#12 8.525 	... 10 more
#12 8.526 Caused by: java.io.IOException: error=0, Failed to exec spawn helper: pid: 62, exit value: 1
#12 8.526 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
#12 8.527 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313)
#12 8.527 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
#12 8.527 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
#12 8.528 	... 12 more
#12 8.528 
#12 8.528 
#12 8.528 * Get more help at https://help.gradle.org
#12 ERROR: process "/bin/sh -c gradle shadowJar --no-daemon --stacktrace" did not complete successfully: exit code: 1
------
 > [build 4/4] RUN gradle shadowJar --no-daemon --stacktrace:
#12 8.525 	... 10 more
#12 8.526 Caused by: java.io.IOException: error=0, Failed to exec spawn helper: pid: 62, exit value: 1
#12 8.526 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
#12 8.527 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313)
#12 8.527 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
#12 8.527 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
#12 8.528 	... 12 more
#12 8.528 
#12 8.528 
#12 8.528 * Get more help at https://help.gradle.org
------
Dockerfile:5
--------------------
   3 |     COPY --chown=gradle:gradle . /home/gradle/src
   4 |     WORKDIR /home/gradle/src
   5 | >>> RUN gradle shadowJar --no-daemon --stacktrace
   6 |     
   7 |     # Build-time metadata stage
--------------------
error: failed to solve: process "/bin/sh -c gradle shadowJar --no-daemon --stacktrace" did not complete successfully: exit code: 1
```

I have no idea why it's not able to spawn JVM process under the hood, might be some kind of a misconfiguration problem with image env.

**Comment by Minecraftschurli** [comment]
the problem is that forking a process on arm64 is not working (idk why)

**Comment by dzikoysk** [comment]
Yeah, I guess it might be associated with these small specific Java images. They recommend to use `--no-daemon`, so I guess that if any task may base on such a behavior, it fill fail. I think I may need to use full linux image during build phase, but I don't know yet how to use it with Java. I guess I may need to install it manually 🤔

**Comment by dzikoysk** [comment]
I think it's Gradle bug, I guess there is nothing I can do tbh. I think I'll provide some kind of a dedicated Docker CI that builds artifacts for arm64 by downloading Reposilite artifact from Maven repository.

**Comment by dzikoysk** [comment]
Finally resolved :) Reposilite 3.x + Nightly builds now support both architectures:

* https://hub.docker.com/r/dzikoysk/reposilite/tags?page=1&ordering=last_updated
