### ISSUE TITLE
FileSystemProvider - Too many open files

### ISSUE THREAD

**Issue by dzikoysk** [dzikoysk/reposilite#657]
```
18:30:44.189 ERROR | java.nio.file.FileSystemException: repositories/releases/org/panda-lang/expressible/1.0.16/expressible-1.0.16.pom: Too many open files
18:30:44.190 ERROR | 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
18:30:44.190 ERROR | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
18:30:44.190 ERROR | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
18:30:44.190 ERROR | 	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
18:30:44.190 ERROR | 	at java.nio.file.Files.newByteChannel(Files.java:361)
18:30:44.190 ERROR | 	at java.nio.file.Files.newByteChannel(Files.java:407)
18:30:44.190 ERROR | 	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
18:30:44.190 ERROR | 	at java.nio.file.Files.newInputStream(Files.java:152)
18:30:44.191 ERROR | 	at com.reposilite.maven.api.FileDetailsKt$toDocumentInfo$1$1.invoke(FileDetails.kt:91)
18:30:44.191 ERROR | 	at com.reposilite.maven.api.FileDetailsKt$toDocumentInfo$1$1.invoke(FileDetails.kt:91)
18:30:44.191 ERROR | 	at com.reposilite.maven.infrastructure.MavenEndpoints$findFile$1$1.invokeSuspend$lambda-1(MavenEndpoints.kt:66)
18:30:44.191 ERROR | 	at panda.std.Result.peek(Result.java:127)
18:30:44.191 ERROR | 	at com.reposilite.maven.infrastructure.MavenEndpoints$findFile$1$1.invokeSuspend(MavenEndpoints.kt:66)
18:30:44.191 ERROR | 	at com.reposilite.maven.infrastructure.MavenEndpoints$findFile$1$1.invoke(MavenEndpoints.kt)
18:30:44.191 ERROR | 	at com.reposilite.maven.infrastructure.MavenEndpoints$findFile$1$1.invoke(MavenEndpoints.kt)
18:30:44.191 ERROR | 	at com.reposilite.web.ContextDsl.accessed(ContextDsl.kt:60)
18:30:44.192 ERROR | 	at com.reposilite.maven.infrastructure.MavenEndpoints$findFile$1.invokeSuspend(MavenEndpoints.kt:63)
18:30:44.192 ERROR | 	at com.reposilite.maven.infrastructure.MavenEndpoints$findFile$1.invoke(MavenEndpoints.kt)
18:30:44.192 ERROR | 	at com.reposilite.maven.infrastructure.MavenEndpoints$findFile$1.invoke(MavenEndpoints.kt)
18:30:44.192 ERROR | 	at com.reposilite.web.ReactiveRoutingKt$createReactiveRouting$plugin$3.invokeSuspend(ReactiveRouting.kt:59)
18:30:44.192 ERROR | 	at com.reposilite.web.ReactiveRoutingKt$createReactiveRouting$plugin$3.invoke(ReactiveRouting.kt)
18:30:44.192 ERROR | 	at com.reposilite.web.ReactiveRoutingKt$createReactiveRouting$plugin$3.invoke(ReactiveRouting.kt)
18:30:44.192 ERROR | 	at com.reposilite.web.routing.ReactiveRoutingPlugin$createHandler$1$2.invokeSuspend(ReactiveRoutingPlugin.kt:70)
18:30:44.192 ERROR | 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
18:30:44.192 ERROR | 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
18:30:44.193 ERROR | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
18:30:44.193 ERROR | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
18:30:44.193 ERROR | 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dzikoysk** [comment]
Probably also related:

```
18:49:42.154 WARN | Transaction attempt #1 failed: org.sqlite.SQLiteException: [SQLITE_CANTOPEN]  Unable to open the database file (unable to open database file). Statement(s): SELECT access_token.id, access_token."name", access_token.secret, access_token.createdAt, access_token.description FROM access_token WHERE access_token."name" = ?: org.jetbrains.exposed.exceptions.ExposedSQLException: org.sqlite.SQLiteException: [SQLITE_CANTOPEN]  Unable to open the database file (unable to open database file)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:49)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:136)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:122)
	at org.jetbrains.exposed.sql.AbstractQuery.iterator(AbstractQuery.kt:65)
	at kotlin.collections.CollectionsKt___CollectionsKt.firstOrNull(_Collections.kt:267)
	at com.reposilite.shared.ExposedExtensionsKt.firstAndMap(ExposedExtensions.kt:43)
	at com.reposilite.token.infrastructure.SqlAccessTokenRepository$findAccessTokenByName$2.invokeSuspend(SqlAccessTokenRepository.kt:192)
	at com.reposilite.token.infrastructure.SqlAccessTokenRepository$findAccessTokenByName$2.invoke(SqlAccessTokenRepository.kt)
	at com.reposilite.token.infrastructure.SqlAccessTokenRepository$findAccessTokenByName$2.invoke(SqlAccessTokenRepository.kt)
	at org.jetbrains.exposed.sql.transactions.experimental.SuspendedKt$suspendedTransactionAsyncInternal$1.invokeSuspend(Suspended.kt:127)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.sqlite.SQLiteException: [SQLITE_CANTOPEN]  Unable to open the database file (unable to open database file)
	at org.sqlite.core.DB.newSQLException(DB.java:1030)
	at org.sqlite.core.DB.newSQLException(DB.java:1042)
	at org.sqlite.core.DB.throwex(DB.java:1007)
	at org.sqlite.core.NativeDB._open_utf8(Native Method)
	at org.sqlite.core.NativeDB._open(NativeDB.java:81)
	at org.sqlite.core.DB.open(DB.java:195)
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:248)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21)
	at org.sqlite.JDBC.createConnection(JDBC.java:115)
	at org.sqlite.JDBC.connect(JDBC.java:90)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.jetbrains.exposed.sql.Database$Companion$connect$10.invoke(Database.kt:184)
	at org.jetbrains.exposed.sql.Database$Companion$connect$10.invoke(Database.kt:184)
	at org.jetbrains.exposed.sql.Database$Companion$doConnect$3.invoke(Database.kt:117)
	at org.jetbrains.exposed.sql.Database$Companion$doConnect$3.invoke(Database.kt:116)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction$connectionLazy$1.invoke(ThreadLocalTransactionManager.kt:60)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction$connectionLazy$1.invoke(ThreadLocalTransactionManager.kt:59)
	at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction.getConnection(ThreadLocalTransactionManager.kt:66)
	at org.jetbrains.exposed.sql.Transaction.getConnection(Transaction.kt)
	at org.jetbrains.exposed.sql.statements.Statement.prepared(Statement.kt:24)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:47)
	... 14 more
18:49:42.155 ERROR | /api/auth/me

```
