### ISSUE TITLE
java.lang.ClassCastException on starting application locally and docker

### ISSUE THREAD

**Issue by mikolayek** [dzikoysk/reposilite#750]
### What happened?

Hi there!
I had couple months ago working reposilite, today I have tried with nightly and reposilite-3.0.0-alpha.2-all.jar to run with default configuration (in the meantime [] have changed to {} for proxied) 

I have used default configuration https://reposilite.com/docs/configuration, run 

`java -jar reposilite-3.0.0-alpha.2-all.jar --config=$(pwd)/config/reposilite.cdn --working-directory=$(pwd)/data/repositories`

where dir-tree is:
```
config
- repositilie.cdn
data
- repositories
- - releases
- - snapshots
- - private
```

I am getting error with ClassCastException (see below)

### Reposilite version

3.x

### Relevant log output

```shell
Exception in thread "main" java.lang.IllegalArgumentException: Cannot load configuration
	at com.reposilite.config.ConfigurationProcessor.tryLoad(ConfigurationProcessor.kt:43)
	at com.reposilite.ReposiliteFactory.createReposilite(ReposiliteFactory.kt:47)
	at com.reposilite.ReposiliteLauncherKt.createWithParameters(ReposiliteLauncher.kt:35)
	at com.reposilite.ReposiliteLauncherKt$main$1.invokeSuspend(ReposiliteLauncher.kt:39)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.reposilite.ReposiliteLauncherKt.main(ReposiliteLauncher.kt:38)
Caused by: java.lang.ClassCastException: class net.dzikoysk.cdn.model.Unit cannot be cast to class net.dzikoysk.cdn.model.Section (net.dzikoysk.cdn.model.Unit and net.dzikoysk.cdn.model.Section are in unnamed module of loader 'app')
	at net.dzikoysk.cdn.composers.ContextualComposers.deserialize(ContextualComposers.java:36)
	at net.dzikoysk.cdn.composers.MapComposer.deserialize(MapComposer.java:74)
	at net.dzikoysk.cdn.CdnDeserializer.deserialize(CdnDeserializer.java:77)
	at net.dzikoysk.cdn.CdnDeserializer.deserialize(CdnDeserializer.java:69)
	at net.dzikoysk.cdn.CdnDeserializer.deserialize(CdnDeserializer.java:39)
	at net.dzikoysk.cdn.Cdn.load(Cdn.java:119)
	at net.dzikoysk.cdn.Cdn.load(Cdn.java:160)
	at net.dzikoysk.cdn.Cdn.load(Cdn.java:133)
	at com.reposilite.config.ConfigurationProcessor.tryLoad(ConfigurationProcessor.kt:30)
	... 12 more
```

**Comment by dzikoysk** [comment]
Hi :)

Reposilite 3.x configuration file is not compatible with 2.x ([as stated in release notes](https://github.com/dzikoysk/reposilite/releases)) and docs are not updated yet for version 3.x (#557) as it's not stable yet. I suggest to just regenerate configuration file or take a look at:

* https://github.com/dzikoysk/reposilite/blob/main/reposilite-backend/src/test/workspace/reposilite.cdn
