### ISSUE TITLE
OutOfMemoryError for proxied files in environment with limited memory resources

### ISSUE THREAD

**Issue by dzikoysk** [dzikoysk/reposilite#763]
### What happened?

Current http client uses array instead of input stream to fetch remote resource

### Reposilite version

3.x

### Relevant log output

```shell
21:26:15.210 ERROR | java.lang.OutOfMemoryError: Java heap space
21:26:15.210 ERROR | 	at java.io.ByteArrayOutputStream.<init>(ByteArrayOutputStream.java:77)
21:26:15.210 ERROR | 	at com.github.kittinunf.fuel.core.requests.DefaultBody.toByteArray(DefaultBody.kt:48)
21:26:15.210 ERROR | 	at com.github.kittinunf.fuel.core.Response.getData(Response.kt:32)
21:26:15.210 ERROR | 	at com.github.kittinunf.fuel.core.deserializers.ByteArrayDeserializer.deserialize(ByteArrayDeserializer.kt:7)
21:26:15.210 ERROR | 	at com.github.kittinunf.fuel.core.deserializers.ByteArrayDeserializer.deserialize(ByteArrayDeserializer.kt:6)
21:26:15.210 ERROR | 	at com.github.kittinunf.fuel.core.DeserializableKt.serializeFor(Deserializable.kt:286)
21:26:15.210 ERROR | 	at com.github.kittinunf.fuel.core.DeserializableKt.awaitResponseResult(Deserializable.kt:277)
21:26:15.210 ERROR | 	at com.reposilite.shared.HttpRemoteClient$get$$inlined$awaitByteArrayResponseResult$default$1.invokeSuspend(Coroutines.kt:79)
21:26:15.210 ERROR | 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
21:26:15.211 ERROR | 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
21:26:15.211 ERROR | 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
21:26:15.211 ERROR | 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
21:26:15.211 ERROR | 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
21:26:15.211 ERROR | 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by dzikoysk** [comment]
Resolved with b3205ca
