### ISSUE TITLE
Too many open files in one-month long run of 3.x

### ISSUE THREAD

**Issue by dzikoysk** [dzikoysk/reposilite#900]
### What happened?

There is probably some kind of an edge case where Reposilite leaks operation on file (could be realted with Exposed + SQLite)

### Reposilite version

3.x

### Relevant log output

```shell
09:05:33.687 WARN | Transaction attempt #0 failed: org.sqlite.SQLiteException: [SQLITE_CANTOPEN]  Unable to open the database file (unable to open database file). Statement(s): INSERT INTO statistics ("count", identifier, identifier_id, "type") VALUES (?, ?, ?, ?) ON CONFLICT("type","identifier_id") DO UPDATE SET "count"=(statistics."count" + ?): org.jetbrains.exposed.exceptions.ExposedSQLException: org.sqlite.SQLiteException: [SQLITE_CANTOPEN]  Unable to open the database file (unable to open database file)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:62)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:135)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:121)
	at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:28)
	at net.dzikoysk.exposed.upsert.ExposedUpsertExtensionsKt.upsert(ExposedUpsertExtensions.kt:17)
	at net.dzikoysk.exposed.upsert.ExposedUpsertExtensionsKt.upsert$default(ExposedUpsertExtensions.kt:11)
	at com.reposilite.statistics.infrastructure.SqlStatisticsRepository.rawIncrementRecord(SqlStatisticsRepository.kt:75)
	at com.reposilite.statistics.infrastructure.SqlStatisticsRepository.access$rawIncrementRecord(SqlStatisticsRepository.kt:51)
	at com.reposilite.statistics.infrastructure.SqlStatisticsRepository$incrementRecords$1.invoke(SqlStatisticsRepository.kt:67)
	at com.reposilite.statistics.infrastructure.SqlStatisticsRepository$incrementRecords$1.invoke(SqlStatisticsRepository.kt:66)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:187)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:213)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:221)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:212)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:164)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:221)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:134)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:131)
	at com.reposilite.statistics.infrastructure.SqlStatisticsRepository.incrementRecords(SqlStatisticsRepository.kt:66)
	at com.reposilite.statistics.StatisticsFacade.saveRecordsBulk(StatisticsFacade.kt:45)
	at com.reposilite.statistics.application.StatisticsWebConfiguration.initialize$lambda-1$lambda-0(StatisticsWebConfiguration.kt:44)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.sqlite.SQLiteException: [SQLITE_CANTOPEN]  Unable to open the database file (unable to open database file)
	at org.sqlite.core.DB.newSQLException(DB.java:1030)
	at org.sqlite.core.DB.newSQLException(DB.java:1042)
	at org.sqlite.core.DB.execute(DB.java:884)
	at org.sqlite.core.DB.executeUpdate(DB.java:922)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:98)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.executeUpdate(JdbcPreparedStatementImpl.kt:26)
	at org.jetbrains.exposed.sql.statements.InsertStatement.execInsertFunction(InsertStatement.kt:118)
	at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:126)
	at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:12)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:60)
	... 24 more
09:05:33.688 WARN | Transaction attempt #1 failed: org.sqlite.SQLiteException: [SQLITE_CANTOPEN]  Unable to open the database file (unable to open database file). Statement(s): INSERT INTO statistics ("count", identifier, identifier_id, "type") VALUES (?, ?, ?, ?) ON CONFLICT("type","identifier_id") DO UPDATE SET "count"=(statistics."count" + ?): org.jetbrains.exposed.exceptions.ExposedSQLException: org.sqlite.SQLiteException: [SQLITE_CANTOPEN]  Unable to open the database file (unable to open database file)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:62)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:135)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:121)
	at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:28)
	at net.dzikoysk.exposed.upsert.ExposedUpsertExtensionsKt.upsert(ExposedUpsertExtensions.kt:17)
	at net.dzikoysk.exposed.upsert.ExposedUpsertExtensionsKt.upsert$default(ExposedUpsertExtensions.kt:11)
	at com.reposilite.statistics.infrastructure.SqlStatisticsRepository.rawIncrementRecord(SqlStatisticsRepository.kt:75)
	at com.reposilite.statistics.infrastructure.SqlStatisticsRepository.access$rawIncrementRecord(SqlStatisticsRepository.kt:51)
	at com.reposilite.statistics.infrastructure.SqlStatisticsRepository$incrementRecords$1.invoke(SqlStatisticsRepository.kt:67)
	at com.reposilite.statistics.infrastructure.SqlStatisticsRepository$incrementRecords$1.invoke(SqlStatisticsRepository.kt:66)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:187)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:213)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:221)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:212)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:164)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:221)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:134)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:131)
	at com.reposilite.statistics.infrastructure.SqlStatisticsRepository.incrementRecords(SqlStatisticsRepository.kt:66)
	at com.reposilite.statistics.StatisticsFacade.saveRecordsBulk(StatisticsFacade.kt:45)
	at com.reposilite.statistics.application.StatisticsWebConfiguration.initialize$lambda-1$lambda-0(StatisticsWebConfiguration.kt:44)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.sqlite.SQLiteException: [SQLITE_CANTOPEN]  Unable to open the database file (unable to open database file)
	at org.sqlite.core.DB.newSQLException(DB.java:1030)
	at org.sqlite.core.DB.newSQLException(DB.java:1042)
	at org.sqlite.core.DB.execute(DB.java:884)
	at org.sqlite.core.DB.executeUpdate(DB.java:922)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:98)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.executeUpdate(JdbcPreparedStatementImpl.kt:26)
	at org.jetbrains.exposed.sql.statements.InsertStatement.execInsertFunction(InsertStatement.kt:118)
	at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:126)
	at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:12)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:60)
	... 24 more
09:05:33.689 WARN | Transaction attempt #2 failed: org.sqlite.SQLiteException: [SQLITE_CANTOPEN]  Unable to open the database file (unable to open database file). Statement(s): INSERT INTO statistics ("count", identifier, identifier_id, "type") VALUES (?, ?, ?, ?) ON CONFLICT("type","identifier_id") DO UPDATE SET "count"=(statistics."count" + ?): org.jetbrains.exposed.exceptions.ExposedSQLException: org.sqlite.SQLiteException: [SQLITE_CANTOPEN]  Unable to open the database file (unable to open database file)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:62)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:135)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:121)
	at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:28)
	at net.dzikoysk.exposed.upsert.ExposedUpsertExtensionsKt.upsert(ExposedUpsertExtensions.kt:17)
	at net.dzikoysk.exposed.upsert.ExposedUpsertExtensionsKt.upsert$default(ExposedUpsertExtensions.kt:11)
	at com.reposilite.statistics.infrastructure.SqlStatisticsRepository.rawIncrementRecord(SqlStatisticsRepository.kt:75)
	at com.reposilite.statistics.infrastructure.SqlStatisticsRepository.access$rawIncrementRecord(SqlStatisticsRepository.kt:51)
	at com.reposilite.statistics.infrastructure.SqlStatisticsRepository$incrementRecords$1.invoke(SqlStatisticsRepository.kt:67)
	at com.reposilite.statistics.infrastructure.SqlStatisticsRepository$incrementRecords$1.invoke(SqlStatisticsRepository.kt:66)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:187)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:213)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:221)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:212)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:164)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:221)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:134)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:131)
	at com.reposilite.statistics.infrastructure.SqlStatisticsRepository.incrementRecords(SqlStatisticsRepository.kt:66)
	at com.reposilite.statistics.StatisticsFacade.saveRecordsBulk(StatisticsFacade.kt:45)
	at com.reposilite.statistics.application.StatisticsWebConfiguration.initialize$lambda-1$lambda-0(StatisticsWebConfiguration.kt:44)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.sqlite.SQLiteException: [SQLITE_CANTOPEN]  Unable to open the database file (unable to open database file)
	at org.sqlite.core.DB.newSQLException(DB.java:1030)
	at org.sqlite.core.DB.newSQLException(DB.java:1042)
	at org.sqlite.core.DB.execute(DB.java:884)
	at org.sqlite.core.DB.executeUpdate(DB.java:922)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:98)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.executeUpdate(JdbcPreparedStatementImpl.kt:26)
	at org.jetbrains.exposed.sql.statements.InsertStatement.execInsertFunction(InsertStatement.kt:118)
	at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:126)
	at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:12)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:60)
	... 24 more
```
```

**Comment by dzikoysk** [comment]
Spotted with:

```
2021-12-29 17:30:32.465 DEBUG | Cannot get https://repository.sonatype.org/content/groups/sonatype-public-grid/org/panda-lang/pandomium/81.2/81.2
2021-12-29 17:30:32.466 DEBUG | java.net.SocketException: Too many open files
2021-12-29 17:30:32.466 DEBUG | 	at java.net.Socket.createImpl(Socket.java:478)
2021-12-29 17:30:32.466 DEBUG | 	at java.net.Socket.connect(Socket.java:605)
2021-12-29 17:30:32.466 DEBUG | 	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:284)
2021-12-29 17:30:32.466 DEBUG | 	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
2021-12-29 17:30:32.466 DEBUG | 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
2021-12-29 17:30:32.466 DEBUG | 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
2021-12-29 17:30:32.466 DEBUG | 	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
2021-12-29 17:30:32.466 DEBUG | 	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
2021-12-29 17:30:32.466 DEBUG | 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
2021-12-29 17:30:32.466 DEBUG | 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
2021-12-29 17:30:32.467 DEBUG | 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
2021-12-29 17:30:32.467 DEBUG | 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
2021-12-29 17:30:32.467 DEBUG | 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167)
2021-12-29 17:30:32.467 DEBUG | 	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:151)
2021-12-29 17:30:32.467 DEBUG | 	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84)
2021-12-29 17:30:32.467 DEBUG | 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012)
2021-12-29 17:30:32.467 DEBUG | 	at com.reposilite.shared.http.HttpRemoteClient.execute(HttpRemoteClient.kt:85)
2021-12-29 17:30:32.467 DEBUG | 	at com.reposilite.shared.http.HttpRemoteClient.head(HttpRemoteClient.kt:47)
2021-12-29 17:30:32.467 DEBUG | 	at com.reposilite.maven.ProxyService$findRemoteDetails$1.invoke(ProxyService.kt:34)
2021-12-29 17:30:32.467 DEBUG | 	at com.reposilite.maven.ProxyService$findRemoteDetails$1.invoke(ProxyService.kt:33)
2021-12-29 17:30:32.467 DEBUG | 	at com.reposilite.maven.ProxyService$searchInRemoteRepositories$2.invoke(ProxyService.kt:47)
2021-12-29 17:30:32.467 DEBUG | 	at com.reposilite.maven.ProxyService$searchInRemoteRepositories$2.invoke(ProxyService.kt:47)
2021-12-29 17:30:32.467 DEBUG | 	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
2021-12-29 17:30:32.467 DEBUG | 	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
2021-12-29 17:30:32.467 DEBUG | 	at com.reposilite.shared.extensions.KotlinExtensionsKt.firstSuccessOr(KotlinExtensions.kt:53)
2021-12-29 17:30:32.467 DEBUG | 	at com.reposilite.shared.extensions.KotlinExtensionsKt.firstOrErrors(KotlinExtensions.kt:41)
2021-12-29 17:30:32.467 DEBUG | 	at com.reposilite.maven.ProxyService.searchInRemoteRepositories(ProxyService.kt:48)
2021-12-29 17:30:32.467 DEBUG | 	at com.reposilite.maven.ProxyService.findRemoteDetails(ProxyService.kt:33)
2021-12-29 17:30:32.467 DEBUG | 	at com.reposilite.maven.MavenFacade$findDetails$1.invoke(MavenFacade.kt:79)
2021-12-29 17:30:32.468 DEBUG | 	at com.reposilite.maven.MavenFacade$findDetails$1.invoke(MavenFacade.kt:77)
2021-12-29 17:30:32.468 DEBUG | 	at com.reposilite.maven.MavenFacade.resolve(MavenFacade.kt:112)
2021-12-29 17:30:32.468 DEBUG | 	at com.reposilite.maven.MavenFacade.findDetails(MavenFacade.kt:77)
2021-12-29 17:30:32.468 DEBUG | 	at com.reposilite.maven.infrastructure.MavenApiEndpoints$findFileDetails$1$1.invoke(MavenApiEndpoints.kt:66)
2021-12-29 17:30:32.468 DEBUG | 	at com.reposilite.maven.infrastructure.MavenApiEndpoints$findFileDetails$1$1.invoke(MavenApiEndpoints.kt:64)
2021-12-29 17:30:32.468 DEBUG | 	at com.reposilite.web.ContextDsl.accessed(ContextDsl.kt:47)
2021-12-29 17:30:32.468 DEBUG | 	at com.reposilite.maven.infrastructure.MavenApiEndpoints$findFileDetails$1.invoke(MavenApiEndpoints.kt:64)
2021-12-29 17:30:32.468 DEBUG | 	at com.reposilite.maven.infrastructure.MavenApiEndpoints$findFileDetails$1.invoke(MavenApiEndpoints.kt:63)
2021-12-29 17:30:32.468 DEBUG | 	at com.reposilite.web.application.RoutingConfigurationKt$createReactiveRouting$plugin$1.invoke(RoutingConfiguration.kt:43)
2021-12-29 17:30:32.468 DEBUG | 	at com.reposilite.web.application.RoutingConfigurationKt$createReactiveRouting$plugin$1.invoke(RoutingConfiguration.kt:39)
2021-12-29 17:30:32.468 DEBUG | 	at com.reposilite.web.routing.RoutingPlugin.createHandler$lambda-3(RoutingPlugin.kt:38)
2021-12-29 17:30:32.468 DEBUG | 	at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:20)
2021-12-29 17:30:32.468 DEBUG | 	at io.javalin.http.JavalinServlet.addHandler$lambda-1(JavalinServlet.kt:115)
2021-12-29 17:30:32.468 DEBUG | 	at io.javalin.http.JavalinServlet.handle$javalin(JavalinServlet.kt:107)
2021-12-29 17:30:32.468 DEBUG | 	at io.javalin.http.JavalinServlet$scopes$2$1$1.invoke(JavalinServlet.kt:40)
2021-12-29 17:30:32.468 DEBUG | 	at io.javalin.http.JavalinServlet$scopes$2$1$1.invoke(JavalinServlet.kt:39)
2021-12-29 17:30:32.468 DEBUG | 	at io.javalin.http.JavalinServletFlow.continueFlow$lambda-6(JavalinServletFlow.kt:78)
2021-12-29 17:30:32.468 DEBUG | 	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
2021-12-29 17:30:32.469 DEBUG | 	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
2021-12-29 17:30:32.469 DEBUG | 	at io.javalin.http.JavalinServletFlow.continueFlow(JavalinServletFlow.kt:72)
2021-12-29 17:30:32.469 DEBUG | 	at io.javalin.http.JavalinServletFlow.continueFlow$lambda-6$lambda-5(JavalinServletFlow.kt:92)
2021-12-29 17:30:32.469 DEBUG | 	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670)
2021-12-29 17:30:32.469 DEBUG | 	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683)
2021-12-29 17:30:32.469 DEBUG | 	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010)
2021-12-29 17:30:32.469 DEBUG | 	at io.javalin.http.JavalinServletFlow.continueFlow$lambda-6(JavalinServletFlow.kt:92)
2021-12-29 17:30:32.469 DEBUG | 	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
2021-12-29 17:30:32.469 DEBUG | 	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
2021-12-29 17:30:32.469 DEBUG | 	at io.javalin.http.JavalinServletFlow.continueFlow(JavalinServletFlow.kt:72)
2021-12-29 17:30:32.469 DEBUG | 	at io.javalin.http.JavalinServletFlow.continueFlow$lambda-6$lambda-5(JavalinServletFlow.kt:92)
2021-12-29 17:30:32.469 DEBUG | 	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670)
2021-12-29 17:30:32.469 DEBUG | 	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683)
2021-12-29 17:30:32.469 DEBUG | 	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010)
2021-12-29 17:30:32.469 DEBUG | 	at io.javalin.http.JavalinServletFlow.continueFlow$lambda-6(JavalinServletFlow.kt:92)
2021-12-29 17:30:32.470 DEBUG | 	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
2021-12-29 17:30:32.470 DEBUG | 	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
2021-12-29 17:30:32.470 DEBUG | 	at io.javalin.http.JavalinServletFlow.continueFlow(JavalinServletFlow.kt:72)
2021-12-29 17:30:32.470 DEBUG | 	at io.javalin.http.JavalinServletFlow.start(JavalinServletFlow.kt:56)
2021-12-29 17:30:32.470 DEBUG | 	at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:92)
2021-12-29 17:30:32.470 DEBUG | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
2021-12-29 17:30:32.470 DEBUG | 	at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58)
2021-12-29 17:30:32.470 DEBUG | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
2021-12-29 17:30:32.470 DEBUG | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
2021-12-29 17:30:32.470 DEBUG | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
2021-12-29 17:30:32.470 DEBUG | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
2021-12-29 17:30:32.470 DEBUG | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
2021-12-29 17:30:32.470 DEBUG | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
2021-12-29 17:30:32.470 DEBUG | 	at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:52)
2021-12-29 17:30:32.470 DEBUG | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
2021-12-29 17:30:32.470 DEBUG | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
2021-12-29 17:30:32.470 DEBUG | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
2021-12-29 17:30:32.470 DEBUG | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
2021-12-29 17:30:32.471 DEBUG | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
2021-12-29 17:30:32.471 DEBUG | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
2021-12-29 17:30:32.471 DEBUG | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
2021-12-29 17:30:32.471 DEBUG | 	at org.eclipse.jetty.server.Server.handle(Server.java:516)
2021-12-29 17:30:32.471 DEBUG | 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
2021-12-29 17:30:32.471 DEBUG | 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
2021-12-29 17:30:32.471 DEBUG | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
2021-12-29 17:30:32.471 DEBUG | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
2021-12-29 17:30:32.471 DEBUG | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
2021-12-29 17:30:32.471 DEBUG | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
2021-12-29 17:30:32.471 DEBUG | 	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
2021-12-29 17:30:32.471 DEBUG | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
2021-12-29 17:30:32.471 DEBUG | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
2021-12-29 17:30:32.471 DEBUG | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
2021-12-29 17:30:32.471 DEBUG | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
2021-12-29 17:30:32.471 DEBUG | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
2021-12-29 17:30:32.471 DEBUG | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
2021-12-29 17:30:32.471 DEBUG | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
2021-12-29 17:30:32.472 DEBUG | 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dzikoysk** [comment]
Problem still exists on alpha.19+, requires new investigation.
