### ISSUE TITLE
Invalid command line parameters lead to non-trivial error message

### ISSUE THREAD

**Issue by Saladoc** [dzikoysk/reposilite#955]
### What happened?

The error message the program crashes with when wrong or invalid command line parameters have been supplied obfuscates the error.  

Wrong parameters lead to picocli not "executing" the `ReposiliteParameters#run` method which in turn results in an UninitializedPropertyAccessException for `localConfigurationPath`. Since the erroneous argument might not have any relation to that property, the exception obfuscates the true error and makes it harder to identify the source of the crash. 

A better error response should be given here.

### Reposilite version

3.x

### Relevant log output

```shell
option '--shared-configuration-mode' (<sharedConfigurationMode>) should be specified only once
Usage: reposilite [full usage message omitted for brevity]
Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property localConfigurationPath has not been initialized
	at com.reposilite.ReposiliteParameters.getLocalConfigurationPath(ReposiliteParameters.kt:43)
	at com.reposilite.settings.SettingsFacade$Companion.createLocalConfiguration(SettingsFacade.kt:34)
	at com.reposilite.settings.application.SettingsWebConfiguration.createLocalConfiguration(SettingsWebConfiguration.kt:22)
	at com.reposilite.ReposiliteFactory.createReposilite(ReposiliteFactory.kt:47)
	at com.reposilite.ReposiliteFactory.createReposilite(ReposiliteFactory.kt:44)
	at com.reposilite.ReposiliteLauncherKt.createWithParameters(ReposiliteLauncher.kt:34)
	at com.reposilite.ReposiliteLauncherKt.main(ReposiliteLauncher.kt:38)
```

**Comment by dzikoysk** [comment]
Thanks, it's fixed in alpha.10. I don't think we need any extra exception handling as it may happen only if the command line class is corrupted, so it's always considered as a bug.
